import { BadRequestException, ConflictException, Injectable, UnauthorizedException } from '@nestjs/common';
import { createHash, createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { DatabaseService } from '../database/database.service';
type Credentials={email:string;password:string}; type Tokens={accessToken:string;refreshToken:string};
@Injectable() export class AuthService {
 constructor(private readonly db:DatabaseService){}
 async register(i:Credentials){const email=this.email(i.email);this.password(i.password);if(await this.db.account.findUnique({where:{email}}))throw new ConflictException('Account exists.');const a=await this.db.account.create({data:{email,passwordHash:this.hash(i.password),person:{create:{firstName:'Pending',lastName:'Profile'}}}});return this.issue(a.id)}
 async login(i:Credentials){const a=await this.db.account.findUnique({where:{email:this.email(i.email)}});if(!a||!this.verify(i.password,a.passwordHash)||a.status==='SUSPENDED'||a.status==='ARCHIVED')throw new UnauthorizedException('Invalid credentials.');return this.issue(a.id)}
 async refresh(refreshToken:string):Promise<Tokens>{const s=await this.db.session.findUnique({where:{tokenHash:this.tokenHash(refreshToken)}});if(!s||s.revokedAt||s.expiresAt<=new Date())throw new UnauthorizedException('Invalid session.');await this.db.session.update({where:{id:s.id},data:{revokedAt:new Date()}});return this.issue(s.accountId)}
 async logout(refreshToken:string):Promise<void>{await this.db.session.updateMany({where:{tokenHash:this.tokenHash(refreshToken),revokedAt:null},data:{revokedAt:new Date()}})}
 private async issue(accountId:string):Promise<Tokens>{const refreshToken=randomBytes(48).toString('base64url');await this.db.session.create({data:{accountId,tokenHash:this.tokenHash(refreshToken),expiresAt:new Date(Date.now()+2592000000)}});return{accessToken:this.access(accountId),refreshToken}}
 private access(id:string){const secret=process.env.JWT_SECRET;if(!secret||secret.length<32)throw new Error('JWT_SECRET required.');const n=Math.floor(Date.now()/1000),e=(v:object)=>Buffer.from(JSON.stringify(v)).toString('base64url'),b=`${e({alg:'HS256',typ:'JWT'})}.${e({sub:id,iat:n,exp:n+900})}`;return `${b}.${createHmac('sha256',secret).update(b).digest('base64url')}`}
 verifyAccessToken(token:string){const[h,p,s]=token.split('.'),secret=process.env.JWT_SECRET;if(!h||!p||!s||!secret)throw new UnauthorizedException();const x=createHmac('sha256',secret).update(`${h}.${p}`).digest('base64url');if(s.length!==x.length||!timingSafeEqual(Buffer.from(s),Buffer.from(x)))throw new UnauthorizedException();const c=JSON.parse(Buffer.from(p,'base64url').toString()) as{sub?:string;exp?:number};if(!c.sub||!c.exp||c.exp<=Math.floor(Date.now()/1000))throw new UnauthorizedException();return{accountId:c.sub}}
 private email(v:string){const e=v?.trim().toLowerCase();if(!e||!/^\S+@\S+\.\S+$/.test(e))throw new BadRequestException('Valid email required.');return e} private password(v:string){if(!v||v.length<12)throw new BadRequestException('Password min 12.')} private hash(v:string){const s=randomBytes(16).toString('hex');return `${s}:${scryptSync(v,s,64).toString('hex')}`} private verify(v:string,x:string){const[s,d]=x.split(':');return!!s&&!!d&&timingSafeEqual(scryptSync(v,s,64),Buffer.from(d,'hex'))} private tokenHash(v:string){return createHash('sha256').update(v).digest('hex')}
}