import {evaluateFinanceForecast,compareFinanceForecastScenarios} from './finance-forecast-control.domain';
function eq(a:unknown,e:unknown,l:string){if(a!==e)throw new Error(`${l}: expected ${e}, got ${a}`)}
function throws(fn:()=>unknown,c:string){try{fn()}catch(e){if(e instanceof Error&&e.message===c)return;throw e}throw new Error(`Expected ${c}`)}
const low=evaluateFinanceForecast({centerOrgUnitId:'c1',scenario:'BASE',openingCashMinor:500000,forecastRevenueMinor:500000,forecastExpenseMinor:400000,forecastCollectionsMinor:300000,forecastReceivableMinor:300000,minimumCashReserveMinor:300000});eq(low.risk,'LOW','low risk');eq(low.projectedCashMinor,900000,'low projected');eq(low.requiresExecutiveReview,false,'low review');
const medium=evaluateFinanceForecast({centerOrgUnitId:'c1',scenario:'DOWNSIDE',openingCashMinor:300000,forecastRevenueMinor:200000,forecastExpenseMinor:450000,forecastCollectionsMinor:100000,forecastReceivableMinor:150000,minimumCashReserveMinor:100000});eq(medium.risk,'MEDIUM','medium risk');eq(medium.requiresExecutiveReview,false,'medium review');
const high=evaluateFinanceForecast({centerOrgUnitId:'c1',scenario:'STRESS',openingCashMinor:300000,forecastRevenueMinor:100000,forecastExpenseMinor:250000,forecastCollectionsMinor:50000,forecastReceivableMinor:200000,minimumCashReserveMinor:250000});eq(high.risk,'HIGH','high risk');eq(high.requiresExecutiveReview,true,'high review');
const critical=evaluateFinanceForecast({centerOrgUnitId:'c1',scenario:'STRESS',openingCashMinor:100000,forecastRevenueMinor:50000,forecastExpenseMinor:300000,forecastCollectionsMinor:25000,forecastReceivableMinor:200000,minimumCashReserveMinor:100000});eq(critical.risk,'CRITICAL','critical risk');eq(critical.projectedCashMinor,-125000,'critical projected');eq(critical.requiresExecutiveReview,true,'critical review');
const comparison=compareFinanceForecastScenarios([{centerOrgUnitId:'c1',scenario:'BASE',openingCashMinor:500000,forecastRevenueMinor:500000,forecastExpenseMinor:400000,forecastCollectionsMinor:300000,forecastReceivableMinor:300000,minimumCashReserveMinor:300000},{centerOrgUnitId:'c1',scenario:'STRESS',openingCashMinor:100000,forecastRevenueMinor:50000,forecastExpenseMinor:300000,forecastCollectionsMinor:25000,forecastReceivableMinor:200000,minimumCashReserveMinor:100000}]);eq(comparison.scenarioCount,2,'scenario count');eq(comparison.criticalCount,1,'critical count');eq(comparison.minimumProjectedCashMinor,-125000,'minimum cash');
throws(()=>compareFinanceForecastScenarios([]),'FINANCE_FORECAST_SCENARIOS_REQUIRED');throws(()=>compareFinanceForecastScenarios([{centerOrgUnitId:'c1',scenario:'BASE',openingCashMinor:0,forecastRevenueMinor:0,forecastExpenseMinor:0,forecastCollectionsMinor:0,forecastReceivableMinor:0,minimumCashReserveMinor:0},{centerOrgUnitId:'c2',scenario:'BASE',openingCashMinor:0,forecastRevenueMinor:0,forecastExpenseMinor:0,forecastCollectionsMinor:0,forecastReceivableMinor:0,minimumCashReserveMinor:0}]),'FINANCE_FORECAST_CENTER_MISMATCH');throws(()=>evaluateFinanceForecast({centerOrgUnitId:'',scenario:'BASE',openingCashMinor:0,forecastRevenueMinor:0,forecastExpenseMinor:0,forecastCollectionsMinor:0,forecastReceivableMinor:0,minimumCashReserveMinor:0}),'FINANCE_FORECAST_CENTER_REQUIRED');throws(()=>evaluateFinanceForecast({centerOrgUnitId:'c1',scenario:'BASE',openingCashMinor:-1,forecastRevenueMinor:0,forecastExpenseMinor:0,forecastCollectionsMinor:0,forecastReceivableMinor:0,minimumCashReserveMinor:0}),'FINANCE_FORECAST_AMOUNT_INVALID');
console.log('Finance L4 forecast control assertions passed.');
