import {evaluateFinanceBudgetControl,assertFinanceBudgetOverride} from './finance-budget-control.domain';
function eq(a:unknown,e:unknown,l:string){if(a!==e)throw new Error(`${l}: expected ${e}, got ${a}`)}
function throws(fn:()=>unknown,c:string){try{fn()}catch(e){if(e instanceof Error&&e.message===c)return;throw e}throw new Error(`Expected ${c}`)}
const healthy=evaluateFinanceBudgetControl({centerOrgUnitId:'c1',budgetMinor:1000000,committedMinor:100000,spentMinor:300000,requestedMinor:100000,approvalLimitMinor:150000});eq(healthy.status,'HEALTHY','healthy status');eq(healthy.decision,'ALLOW','healthy decision');eq(healthy.projectedMinor,500000,'healthy projected');
const approval=evaluateFinanceBudgetControl({centerOrgUnitId:'c2',budgetMinor:1000000,committedMinor:100000,spentMinor:500000,requestedMinor:200000,approvalLimitMinor:150000});eq(approval.decision,'REVIEW_REQUIRED','approval limit');
const watch=evaluateFinanceBudgetControl({centerOrgUnitId:'c3',budgetMinor:1000000,committedMinor:200000,spentMinor:600000,requestedMinor:50000,approvalLimitMinor:100000});eq(watch.status,'WATCH','watch status');eq(watch.decision,'REVIEW_REQUIRED','watch decision');
const blocked=evaluateFinanceBudgetControl({centerOrgUnitId:'c4',budgetMinor:1000000,committedMinor:300000,spentMinor:650000,requestedMinor:100000,approvalLimitMinor:200000});eq(blocked.status,'EXCEEDED','exceeded status');eq(blocked.decision,'BLOCK','exceeded decision');eq(blocked.remainingMinor,50000,'remaining');
eq(assertFinanceBudgetOverride({decision:'ALLOW',requestedBy:'a1'}),true,'allow no override');eq(assertFinanceBudgetOverride({decision:'BLOCK',requestedBy:'a1',approvedBy:'a2',reason:'Emergency operational requirement'}),true,'approved override');
throws(()=>assertFinanceBudgetOverride({decision:'BLOCK',requestedBy:'a1'}),'FINANCE_BUDGET_OVERRIDE_APPROVAL_REQUIRED');throws(()=>assertFinanceBudgetOverride({decision:'BLOCK',requestedBy:'a1',approvedBy:'a1',reason:'Emergency operational requirement'}),'FINANCE_BUDGET_OVERRIDE_SOD_VIOLATION');throws(()=>assertFinanceBudgetOverride({decision:'BLOCK',requestedBy:'a1',approvedBy:'a2',reason:'short'}),'FINANCE_BUDGET_OVERRIDE_REASON_REQUIRED');
throws(()=>evaluateFinanceBudgetControl({centerOrgUnitId:'',budgetMinor:0,committedMinor:0,spentMinor:0,requestedMinor:0,approvalLimitMinor:0}),'FINANCE_BUDGET_CENTER_REQUIRED');throws(()=>evaluateFinanceBudgetControl({centerOrgUnitId:'c1',budgetMinor:-1,committedMinor:0,spentMinor:0,requestedMinor:0,approvalLimitMinor:0}),'FINANCE_BUDGET_AMOUNT_INVALID');
console.log('Finance L4 budget control assertions passed.');
