import {evaluateFinanceRiskCompliance,assertFinanceComplianceResolution} from './finance-risk-compliance.domain';
function eq(a:unknown,e:unknown,l:string){if(a!==e)throw new Error(`${l}: expected ${e}, got ${a}`)}
function throws(fn:()=>unknown,c:string){try{fn()}catch(e){if(e instanceof Error&&e.message===c)return;throw e}throw new Error(`Expected ${c}`)}
const clear=evaluateFinanceRiskCompliance({centerOrgUnitId:'c1',unreconciledPaymentCount:0,unresolvedVarianceCount:0,overdueReceivableMinor:0,overduePayableMinor:0,unauthorizedAdjustmentCount:0,signals:[]});eq(clear.decision,'CLEAR','clear decision');eq(clear.openSignalCount,0,'clear signals');
const review=evaluateFinanceRiskCompliance({centerOrgUnitId:'c2',unreconciledPaymentCount:2,unresolvedVarianceCount:1,overdueReceivableMinor:50000,overduePayableMinor:0,unauthorizedAdjustmentCount:0,signals:[{code:'DOC_EXPIRY',severity:'WARNING',open:true}]});eq(review.decision,'REVIEW_REQUIRED','review decision');eq(review.openSignalCount,1,'review signals');
const high=evaluateFinanceRiskCompliance({centerOrgUnitId:'c3',unreconciledPaymentCount:0,unresolvedVarianceCount:0,overdueReceivableMinor:0,overduePayableMinor:0,unauthorizedAdjustmentCount:0,signals:[{code:'POLICY_BREACH',severity:'HIGH',open:true,amountMinor:1000}]});eq(high.decision,'REVIEW_REQUIRED','high signal review');eq(high.highSignalCount,1,'high count');
const critical=evaluateFinanceRiskCompliance({centerOrgUnitId:'c4',unreconciledPaymentCount:0,unresolvedVarianceCount:0,overdueReceivableMinor:0,overduePayableMinor:0,unauthorizedAdjustmentCount:0,signals:[{code:'LEDGER_TAMPER',severity:'CRITICAL',open:true}]});eq(critical.decision,'ESCALATION_REQUIRED','critical escalation');eq(critical.criticalSignalCount,1,'critical count');
const unauthorized=evaluateFinanceRiskCompliance({centerOrgUnitId:'c5',unreconciledPaymentCount:0,unresolvedVarianceCount:0,overdueReceivableMinor:0,overduePayableMinor:0,unauthorizedAdjustmentCount:1,signals:[]});eq(unauthorized.decision,'ESCALATION_REQUIRED','unauthorized escalation');
const closed=evaluateFinanceRiskCompliance({centerOrgUnitId:'c6',unreconciledPaymentCount:0,unresolvedVarianceCount:0,overdueReceivableMinor:0,overduePayableMinor:0,unauthorizedAdjustmentCount:0,signals:[{code:'OLD',severity:'CRITICAL',open:false}]});eq(closed.decision,'CLEAR','closed ignored');eq(closed.openSignalCount,0,'closed signal count');
eq(assertFinanceComplianceResolution({decision:'REVIEW_REQUIRED',resolvedBy:'a1',reason:'Reviewed supporting evidence'}),true,'review resolution');eq(assertFinanceComplianceResolution({decision:'ESCALATION_REQUIRED',resolvedBy:'a1',approvedBy:'a2',reason:'Approved after independent review'}),true,'escalation resolution');
throws(()=>assertFinanceComplianceResolution({decision:'ESCALATION_REQUIRED',resolvedBy:'a1',reason:'Independent review required'}),'FINANCE_COMPLIANCE_APPROVAL_REQUIRED');throws(()=>assertFinanceComplianceResolution({decision:'ESCALATION_REQUIRED',resolvedBy:'a1',approvedBy:'a1',reason:'Independent review required'}),'FINANCE_COMPLIANCE_SOD_VIOLATION');throws(()=>assertFinanceComplianceResolution({decision:'CLEAR',resolvedBy:'a1',reason:'short'}),'FINANCE_COMPLIANCE_RESOLUTION_INVALID');
throws(()=>evaluateFinanceRiskCompliance({centerOrgUnitId:'',unreconciledPaymentCount:0,unresolvedVarianceCount:0,overdueReceivableMinor:0,overduePayableMinor:0,unauthorizedAdjustmentCount:0,signals:[]}),'FINANCE_COMPLIANCE_CENTER_REQUIRED');throws(()=>evaluateFinanceRiskCompliance({centerOrgUnitId:'c1',unreconciledPaymentCount:-1,unresolvedVarianceCount:0,overdueReceivableMinor:0,overduePayableMinor:0,unauthorizedAdjustmentCount:0,signals:[]}),'FINANCE_COMPLIANCE_COUNT_INVALID');throws(()=>evaluateFinanceRiskCompliance({centerOrgUnitId:'c1',unreconciledPaymentCount:0,unresolvedVarianceCount:0,overdueReceivableMinor:-1,overduePayableMinor:0,unauthorizedAdjustmentCount:0,signals:[]}),'FINANCE_COMPLIANCE_AMOUNT_INVALID');throws(()=>evaluateFinanceRiskCompliance({centerOrgUnitId:'c1',unreconciledPaymentCount:0,unresolvedVarianceCount:0,overdueReceivableMinor:0,overduePayableMinor:0,unauthorizedAdjustmentCount:0,signals:[{code:'',severity:'HIGH',open:true}]}),'FINANCE_COMPLIANCE_SIGNAL_INVALID');
console.log('Finance L4 risk and compliance assertions passed.');
