import {evaluateFinanceExecutiveControl,buildFinanceExecutivePortfolio} from './finance-executive-control.domain';
function eq(a:unknown,e:unknown,l:string){if(a!==e)throw new Error(`${l}: expected ${e}, got ${a}`)}
function throws(fn:()=>unknown,c:string){try{fn()}catch(e){if(e instanceof Error&&e.message===c)return;throw e}throw new Error(`Expected ${c}`)}
const clear=evaluateFinanceExecutiveControl({centerOrgUnitId:'c1',revenueMinor:1000000,expenseMinor:500000,receivableMinor:100000, cashVarianceMinor:0,overdueReceivableMinor:10000,unresolvedFindingCount:0,criticalFindingCount:0});eq(clear.risk,'LOW','clear risk');eq(clear.decision,'CLEAR','clear decision');eq(clear.netMinor,500000,'net');
const medium=evaluateFinanceExecutiveControl({centerOrgUnitId:'c2',revenueMinor:1000000,expenseMinor:760000,receivableMinor:100000,cashVarianceMinor:1000,overdueReceivableMinor:26000,unresolvedFindingCount:1,criticalFindingCount:0});eq(medium.risk,'MEDIUM','medium risk');eq(medium.decision,'REVIEW_REQUIRED','medium decision');
const high=evaluateFinanceExecutiveControl({centerOrgUnitId:'c3',revenueMinor:1000000,expenseMinor:910000,receivableMinor:100000,cashVarianceMinor:0,overdueReceivableMinor:51000,unresolvedFindingCount:5,criticalFindingCount:0});eq(high.risk,'HIGH','high risk');eq(high.decision,'REVIEW_REQUIRED','high decision');
const critical=evaluateFinanceExecutiveControl({centerOrgUnitId:'c4',revenueMinor:1000000,expenseMinor:500000,receivableMinor:100000,cashVarianceMinor:-100000,overdueReceivableMinor:10000,unresolvedFindingCount:0,criticalFindingCount:1});eq(critical.risk,'CRITICAL','critical risk');eq(critical.decision,'ESCALATION_REQUIRED','critical decision');eq(critical.absoluteVarianceMinor,100000,'absolute variance');
const portfolio=buildFinanceExecutivePortfolio([{centerOrgUnitId:'c1',revenueMinor:1000000,expenseMinor:500000,receivableMinor:100000,cashVarianceMinor:0,overdueReceivableMinor:10000,unresolvedFindingCount:0,criticalFindingCount:0},{centerOrgUnitId:'c4',revenueMinor:1000000,expenseMinor:500000,receivableMinor:100000,cashVarianceMinor:-100000,overdueReceivableMinor:10000,unresolvedFindingCount:0,criticalFindingCount:1}]);eq(portfolio.centerCount,2,'portfolio count');eq(portfolio.clearCount,1,'portfolio clear');eq(portfolio.escalationCount,1,'portfolio escalation');
throws(()=>evaluateFinanceExecutiveControl({centerOrgUnitId:'',revenueMinor:0,expenseMinor:0,receivableMinor:0,cashVarianceMinor:0,overdueReceivableMinor:0,unresolvedFindingCount:0,criticalFindingCount:0}),'FINANCE_EXECUTIVE_CENTER_REQUIRED');
throws(()=>evaluateFinanceExecutiveControl({centerOrgUnitId:'c1',revenueMinor:-1,expenseMinor:0,receivableMinor:0,cashVarianceMinor:0,overdueReceivableMinor:0,unresolvedFindingCount:0,criticalFindingCount:0}),'FINANCE_EXECUTIVE_AMOUNT_INVALID');
throws(()=>evaluateFinanceExecutiveControl({centerOrgUnitId:'c1',revenueMinor:0,expenseMinor:0,receivableMinor:0,cashVarianceMinor:1.5,overdueReceivableMinor:0,unresolvedFindingCount:0,criticalFindingCount:0}),'FINANCE_EXECUTIVE_VARIANCE_INVALID');
console.log('Finance L4 executive control assertions passed.');
