import {evaluateFinanceTreasuryControl,buildFinanceTreasuryPortfolio} from './finance-treasury-control.domain';
function eq(a:unknown,e:unknown,l:string){if(a!==e)throw new Error(`${l}: expected ${e}, got ${a}`)}
function throws(fn:()=>unknown,c:string){try{fn()}catch(e){if(e instanceof Error&&e.message===c)return;throw e}throw new Error(`Expected ${c}`)}
const clear=evaluateFinanceTreasuryControl({centerOrgUnitId:'c1',availableCashMinor:1000000,expectedInflowsMinor:500000,dueOutflowsMinor:500000,reserveRequirementMinor:500000,overduePayablesMinor:0});eq(clear.risk,'LOW','clear risk');eq(clear.decision,'CLEAR','clear decision');eq(clear.projectedLiquidityMinor,1000000,'clear liquidity');
const medium=evaluateFinanceTreasuryControl({centerOrgUnitId:'c2',availableCashMinor:600000,expectedInflowsMinor:0,dueOutflowsMinor:500000,reserveRequirementMinor:100000,overduePayablesMinor:0});eq(medium.risk,'MEDIUM','medium risk');eq(medium.decision,'REVIEW_REQUIRED','medium decision');
const high=evaluateFinanceTreasuryControl({centerOrgUnitId:'c3',availableCashMinor:400000,expectedInflowsMinor:0,dueOutflowsMinor:500000,reserveRequirementMinor:0,overduePayablesMinor:0});eq(high.risk,'CRITICAL','negative liquidity critical');eq(high.decision,'ESCALATION_REQUIRED','negative liquidity escalation');
const reserve=evaluateFinanceTreasuryControl({centerOrgUnitId:'c4',availableCashMinor:700000,expectedInflowsMinor:0,dueOutflowsMinor:500000,reserveRequirementMinor:300000,overduePayablesMinor:0});eq(reserve.risk,'HIGH','reserve gap high');eq(reserve.reserveGapMinor,100000,'reserve gap');
const overdue=evaluateFinanceTreasuryControl({centerOrgUnitId:'c5',availableCashMinor:100000,expectedInflowsMinor:0,dueOutflowsMinor:300000,reserveRequirementMinor:0,overduePayablesMinor:50000});eq(overdue.risk,'CRITICAL','overdue critical');eq(overdue.decision,'ESCALATION_REQUIRED','overdue escalation');
const portfolio=buildFinanceTreasuryPortfolio([{centerOrgUnitId:'c1',availableCashMinor:1000000,expectedInflowsMinor:500000,dueOutflowsMinor:500000,reserveRequirementMinor:500000,overduePayablesMinor:0},{centerOrgUnitId:'c5',availableCashMinor:100000,expectedInflowsMinor:0,dueOutflowsMinor:300000,reserveRequirementMinor:0,overduePayablesMinor:50000}]);eq(portfolio.centerCount,2,'portfolio count');eq(portfolio.clearCount,1,'portfolio clear');eq(portfolio.escalationCount,1,'portfolio escalation');eq(portfolio.totalProjectedLiquidityMinor,800000,'portfolio liquidity');
throws(()=>evaluateFinanceTreasuryControl({centerOrgUnitId:'',availableCashMinor:0,expectedInflowsMinor:0,dueOutflowsMinor:0,reserveRequirementMinor:0,overduePayablesMinor:0}),'FINANCE_TREASURY_CENTER_REQUIRED');throws(()=>evaluateFinanceTreasuryControl({centerOrgUnitId:'c1',availableCashMinor:-1,expectedInflowsMinor:0,dueOutflowsMinor:0,reserveRequirementMinor:0,overduePayablesMinor:0}),'FINANCE_TREASURY_AMOUNT_INVALID');
console.log('Finance L4 treasury control assertions passed.');
