import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { AuditService } from '../audit/audit.service';
import { DatabaseService } from '../database/database.service';
import { NotificationsService } from '../notifications/notifications.service';

type RentalItemInput={resourceId?:string;equipmentType?:string|null;size?:string|null;unitPriceSar?:number};
type RentalRow={id:string;renterAccountId:string;status:string;paymentStatus:string;totalHalala:bigint;invoiceNumber:string;whatsappPhone:string|null;reservedAt:Date;paidAt:Date|null;returnedAt:Date|null;createdByAccountId:string;createdAt:Date;updatedAt:Date};
type RentalItemRow={id:string;rentalId:string;resourceId:string;equipmentType:string|null;size:string|null;unitPriceHalala:bigint;assetCodeSnapshot:string;equipmentNameSnapshot:string;serialNumberSnapshot:string|null;returnedAt:Date|null;returnCondition:'OK'|'DAMAGED'|'REVIEW'|null;returnNotes:string|null};

@Injectable()
export class EquipmentRentalService{
  constructor(private readonly db:DatabaseService,private readonly audit:AuditService,private readonly notifications:NotificationsService){}
  private toHalala(value?:number){if(value===undefined||!Number.isFinite(value)||value<0)throw new BadRequestException('Rental price must be zero or greater.');return BigInt(Math.round(value*100));}
  private invoiceNumber(){return `HYD-RNT-${Date.now().toString(36).toUpperCase()}`;}
  private serialize(rental:RentalRow,items:RentalItemRow[]){const returnedCount=items.filter(item=>item.returnedAt).length;return{...rental,totalHalala:Number(rental.totalHalala),returnedCount,pendingReturnCount:items.length-returnedCount,items:items.map(item=>({...item,unitPriceHalala:Number(item.unitPriceHalala)}))};}

  async create(actorAccountId:string,input:{renterAccountId?:string;whatsappPhone?:string|null;items?:RentalItemInput[]}){
    const renterAccountId=input.renterAccountId?.trim();if(!renterAccountId)throw new BadRequestException('Renter account is required.');
    const renter=await this.db.account.findUnique({where:{id:renterAccountId},select:{id:true,status:true}});if(!renter||renter.status!=='ACTIVE')throw new BadRequestException('Renter account is missing or inactive.');
    const items=input.items||[];if(!items.length)throw new BadRequestException('At least one rental equipment item is required.');
    const prepared=[] as Array<{resourceId:string;equipmentType:string|null;size:string|null;unitPriceHalala:bigint;assetCode:string;name:string;serialNumber:string|null}>;
    for(const item of items){const resourceId=item.resourceId?.trim();if(!resourceId)throw new BadRequestException('Equipment resource is required.');const rows=await this.db.$queryRaw<Array<{resourceId:string;assetCode:string;serialNumber:string|null;stockStatus:string;resourceName:string}>>`SELECT b."resourceId",b."assetCode",b."serialNumber",b."stockStatus",r."name" AS "resourceName" FROM "EquipmentBarcode" b JOIN "CalendarResource" r ON r."id"=b."resourceId" WHERE b."resourceId"=${resourceId} LIMIT 1`;const equipment=rows[0];if(!equipment)throw new NotFoundException('Rental equipment not found.');if(equipment.stockStatus!=='AVAILABLE')throw new ConflictException(`${equipment.assetCode} is not available for rental.`);prepared.push({resourceId,equipmentType:item.equipmentType?.trim()||null,size:item.size?.trim()||null,unitPriceHalala:this.toHalala(item.unitPriceSar),assetCode:equipment.assetCode,name:equipment.resourceName,serialNumber:equipment.serialNumber});}
    const totalHalala=prepared.reduce((sum:number,item)=>sum+Number(item.unitPriceHalala),0),invoiceNumber=this.invoiceNumber(),whatsappPhone=input.whatsappPhone?.trim()||null;
    const result=await this.db.serializable(async tx=>{const rentals=await tx.$queryRaw<RentalRow[]>`INSERT INTO "EquipmentRental"("id","renterAccountId","status","paymentStatus","totalHalala","invoiceNumber","whatsappPhone","reservedAt","createdByAccountId","createdAt","updatedAt") VALUES(gen_random_uuid()::text,${renterAccountId},'RESERVED','PENDING',${BigInt(totalHalala)},${invoiceNumber},${whatsappPhone},NOW(),${actorAccountId},NOW(),NOW()) RETURNING *`;const rental=rentals[0],created:RentalItemRow[]=[];for(const item of prepared){const rows=await tx.$queryRaw<RentalItemRow[]>`INSERT INTO "EquipmentRentalItem"("id","rentalId","resourceId","equipmentType","size","unitPriceHalala","assetCodeSnapshot","equipmentNameSnapshot","serialNumberSnapshot","createdAt") VALUES(gen_random_uuid()::text,${rental.id},${item.resourceId},${item.equipmentType},${item.size},${item.unitPriceHalala},${item.assetCode},${item.name},${item.serialNumber},NOW()) RETURNING *`;created.push(rows[0]);}return{rental,items:created};});
    await this.audit.record({actorId:actorAccountId,action:'EQUIPMENT_RENTAL_RESERVED',resource:'EquipmentRental',resourceId:result.rental.id,metadata:{renterAccountId,invoiceNumber,totalHalala,itemCount:prepared.length}});
    return this.serialize(result.rental,result.items);
  }

  async markPaid(actorAccountId:string,id:string){
    const rentals=await this.db.$queryRaw<RentalRow[]>`SELECT * FROM "EquipmentRental" WHERE "id"=${id} LIMIT 1`;const rental=rentals[0];if(!rental)throw new NotFoundException('Rental not found.');if(rental.paymentStatus==='PAID')return this.get(id);if(rental.status==='CANCELLED')throw new ConflictException('Cancelled rental cannot be paid.');
    const items=await this.db.$queryRaw<RentalItemRow[]>`SELECT * FROM "EquipmentRentalItem" WHERE "rentalId"=${id} ORDER BY "createdAt"`;
    await this.db.serializable(async tx=>{for(const item of items){const rows=await tx.$queryRaw<Array<{stockStatus:string}>>`SELECT "stockStatus" FROM "EquipmentBarcode" WHERE "resourceId"=${item.resourceId} FOR UPDATE`;if(rows[0]?.stockStatus!=='AVAILABLE')throw new ConflictException(`${item.assetCodeSnapshot} is no longer available.`);await tx.$executeRaw`INSERT INTO "EquipmentMovement"("id","resourceId","movementType","fromLocation","toLocation","tripId","assignedAccountId","notes","actorAccountId","occurredAt") SELECT gen_random_uuid()::text,${item.resourceId},'CHECK_OUT',"location",NULL,NULL,${rental.renterAccountId},${`Rental ${rental.invoiceNumber}`},${actorAccountId},NOW() FROM "EquipmentBarcode" WHERE "resourceId"=${item.resourceId}`;await tx.$executeRaw`UPDATE "EquipmentBarcode" SET "stockStatus"='CHECKED_OUT',"updatedAt"=NOW() WHERE "resourceId"=${item.resourceId}`;}await tx.$executeRaw`UPDATE "EquipmentRental" SET "status"='ACTIVE',"paymentStatus"='PAID',"paidAt"=NOW(),"updatedAt"=NOW() WHERE "id"=${id}`;});
    const invoice=await this.get(id);await this.notifications.notify(rental.renterAccountId,'EQUIPMENT_RENTAL_INVOICE',{title:'فاتورة تأجير معدات',invoiceNumber:rental.invoiceNumber,rentalId:id,totalHalala:Number(rental.totalHalala),items:invoice.items,message:'تم تأكيد الدفع وحجز معداتك. الفاتورة متاحة داخل التطبيق.'});
    await this.audit.record({actorId:actorAccountId,action:'EQUIPMENT_RENTAL_PAID',resource:'EquipmentRental',resourceId:id,metadata:{invoiceNumber:rental.invoiceNumber,renterAccountId:rental.renterAccountId,totalHalala:Number(rental.totalHalala),whatsappPrepared:Boolean(rental.whatsappPhone)}});
    return invoice;
  }

  async get(id:string){const rentals=await this.db.$queryRaw<RentalRow[]>`SELECT * FROM "EquipmentRental" WHERE "id"=${id} LIMIT 1`;if(!rentals[0])throw new NotFoundException('Rental not found.');const items=await this.db.$queryRaw<RentalItemRow[]>`SELECT * FROM "EquipmentRentalItem" WHERE "rentalId"=${id} ORDER BY "createdAt"`;return this.serialize(rentals[0],items);}
  async getMine(accountId:string,id:string){const rental=await this.get(id);if(rental.renterAccountId!==accountId)throw new NotFoundException('Rental not found.');return rental;}
  async mine(accountId:string){const rows=await this.db.$queryRaw<RentalRow[]>`SELECT * FROM "EquipmentRental" WHERE "renterAccountId"=${accountId} ORDER BY "createdAt" DESC LIMIT 100`;return Promise.all(rows.map((row:RentalRow)=>this.get(row.id)));}

  async returnScan(actorAccountId:string,id:string,input:{code?:string;condition?:'OK'|'DAMAGED'|'REVIEW';notes?:string|null;toLocation?:string|null}){
    const code=input.code?.trim();if(!code)throw new BadRequestException('Barcode or QR code is required for return.');const condition=input.condition||'OK';if(!['OK','DAMAGED','REVIEW'].includes(condition))throw new BadRequestException('Invalid return condition.');
    const rentals=await this.db.$queryRaw<RentalRow[]>`SELECT * FROM "EquipmentRental" WHERE "id"=${id} LIMIT 1`;const rental=rentals[0];if(!rental)throw new NotFoundException('Rental not found.');if(rental.status!=='ACTIVE')throw new ConflictException('Only active rentals can receive equipment returns.');
    const equipment=await this.db.$queryRaw<Array<{resourceId:string;assetCode:string;stockStatus:string;location:string|null}>>`SELECT "resourceId","assetCode","stockStatus","location" FROM "EquipmentBarcode" WHERE "barcodeValue"=${code} OR "qrValue"=${code} OR "assetCode"=${code} OR "serialNumber"=${code} LIMIT 1`;const asset=equipment[0];if(!asset)throw new NotFoundException('Equipment code not found.');
    const items=await this.db.$queryRaw<RentalItemRow[]>`SELECT * FROM "EquipmentRentalItem" WHERE "rentalId"=${id} AND "resourceId"=${asset.resourceId} LIMIT 1`;const item=items[0];if(!item)throw new ConflictException('Scanned equipment does not belong to this rental.');if(item.returnedAt)return this.get(id);
    const notes=input.notes?.trim()||null,toLocation=input.toLocation?.trim()||asset.location||null,nextStatus=condition==='OK'?'AVAILABLE':'QUARANTINED';
    await this.db.serializable(async tx=>{const locked=await tx.$queryRaw<Array<{stockStatus:string;location:string|null}>>`SELECT "stockStatus","location" FROM "EquipmentBarcode" WHERE "resourceId"=${asset.resourceId} FOR UPDATE`;if(locked[0]?.stockStatus!=='CHECKED_OUT')throw new ConflictException('Equipment is not currently checked out.');await tx.$executeRaw`UPDATE "EquipmentRentalItem" SET "returnedAt"=NOW(),"returnCondition"=${condition},"returnNotes"=${notes} WHERE "id"=${item.id} AND "returnedAt" IS NULL`;await tx.$executeRaw`INSERT INTO "EquipmentMovement"("id","resourceId","movementType","fromLocation","toLocation","tripId","assignedAccountId","notes","actorAccountId","occurredAt") VALUES(gen_random_uuid()::text,${asset.resourceId},${condition==='OK'?'CHECK_IN':'QUARANTINE'},${locked[0].location},${toLocation},NULL,${rental.renterAccountId},${notes||`Rental return ${rental.invoiceNumber}`},${actorAccountId},NOW())`;await tx.$executeRaw`UPDATE "EquipmentBarcode" SET "stockStatus"=${nextStatus},"location"=COALESCE(${toLocation},"location"),"updatedAt"=NOW() WHERE "resourceId"=${asset.resourceId}`;const pending=await tx.$queryRaw<Array<{count:bigint}>>`SELECT COUNT(*)::bigint AS "count" FROM "EquipmentRentalItem" WHERE "rentalId"=${id} AND "returnedAt" IS NULL`;if(Number(pending[0]?.count||0)===0)await tx.$executeRaw`UPDATE "EquipmentRental" SET "status"='RETURNED',"returnedAt"=NOW(),"updatedAt"=NOW() WHERE "id"=${id}`;});
    const updated=await this.get(id);await this.audit.record({actorId:actorAccountId,action:'EQUIPMENT_RENTAL_ITEM_RETURNED',resource:'EquipmentRental',resourceId:id,metadata:{invoiceNumber:rental.invoiceNumber,resourceId:asset.resourceId,assetCode:asset.assetCode,condition,stockStatus:nextStatus,notes}});if(updated.status==='RETURNED'){await this.notifications.notify(rental.renterAccountId,'EQUIPMENT_RENTAL_RETURNED',{title:'تم استلام معدات التأجير',invoiceNumber:rental.invoiceNumber,rentalId:id,message:'تم استلام جميع معدات التأجير وإغلاق عملية الإيجار.'});await this.audit.record({actorId:actorAccountId,action:'EQUIPMENT_RENTAL_RETURNED',resource:'EquipmentRental',resourceId:id,metadata:{invoiceNumber:rental.invoiceNumber,renterAccountId:rental.renterAccountId}});}return updated;
  }

  async shareInvoice(actorAccountId:string,id:string,input:{accountId?:string;channel?:'IN_APP'|'WHATSAPP'}){const rental=await this.get(id);const accountId=input.accountId?.trim()||rental.renterAccountId,channel=input.channel||'IN_APP';if(channel==='WHATSAPP'){await this.audit.record({actorId:actorAccountId,action:'EQUIPMENT_RENTAL_WHATSAPP_PREPARED',resource:'EquipmentRental',resourceId:id,metadata:{invoiceNumber:rental.invoiceNumber,recipientPhone:rental.whatsappPhone}});return{channel:'WHATSAPP',status:'PROVIDER_NOT_CONNECTED',phone:rental.whatsappPhone,invoice:rental};}await this.notifications.notify(accountId,'EQUIPMENT_RENTAL_INVOICE_SHARED',{title:'فاتورة تأجير معدات',invoiceNumber:rental.invoiceNumber,rentalId:id,totalHalala:rental.totalHalala,items:rental.items});await this.audit.record({actorId:actorAccountId,action:'EQUIPMENT_RENTAL_INVOICE_SHARED',resource:'EquipmentRental',resourceId:id,metadata:{accountId,channel:'IN_APP'}});return{channel:'IN_APP',status:'SENT',accountId};}
}
