(()=>{
  const section=document.getElementById('store');if(!section)return;
  const grid=section.querySelector('.product-grid');
  const toast=m=>{const t=document.getElementById('toast');if(!t)return;t.textContent=m;t.classList.add('visible');setTimeout(()=>t.classList.remove('visible'),2200)};
  const cart=new Map();
  const money=(v,c='SAR')=>new Intl.NumberFormat('ar-SA',{style:'currency',currency:c}).format(v/100);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const panel=document.createElement('div');panel.className='hl-store-cart';panel.innerHTML='<strong>السلة</strong><span class="hl-store-summary">السلة فارغة</span><button type="button" class="hl-store-checkout" disabled>إنشاء الطلب</button><button type="button" class="hl-store-orders">طلباتي</button><div class="hl-store-orders-list" hidden></div>';section.appendChild(panel);
  const summary=panel.querySelector('.hl-store-summary'),checkout=panel.querySelector('.hl-store-checkout'),orders=panel.querySelector('.hl-store-orders-list');
  const renderCart=()=>{let n=0,total=0;for(const x of cart.values()){n+=x.quantity;total+=x.priceMinor*x.quantity}summary.textContent=n?(n+' منتج · '+money(total)):'السلة فارغة';checkout.disabled=!n};
  const loadProducts=async()=>{grid.innerHTML='<article><span>جارٍ تحميل المنتجات...</span></article>';try{const base=window.HydrolandAuth?.apiBase||'https://hydroland.onrender.com/api/v1';const r=await fetch(base+'/store/products');const products=await r.json();if(!r.ok||!Array.isArray(products))throw new Error();if(!products.length){grid.innerHTML='<article><span>لا توجد منتجات متاحة حاليًا.</span></article>';return}grid.innerHTML=products.map(p=>'<article><div class="product-art">◉</div><small>'+esc(p.sku)+'</small><span>'+esc(p.nameAr)+'</span><strong>'+money(p.priceMinor,p.currency)+'</strong><small>المتوفر: '+p.stockQuantity+'</small><button type="button" data-store-add="'+esc(p.id)+'" '+(p.stockQuantity<1?'disabled':'')+'>'+(p.stockQuantity<1?'نفد المخزون':'أضف للسلة')+'</button></article>').join('');grid.querySelectorAll('[data-store-add]').forEach(btn=>btn.addEventListener('click',()=>{const p=products.find(x=>x.id===btn.dataset.storeAdd);if(!p)return;const q=cart.get(p.id)?.quantity||0;if(q>=p.stockQuantity){toast('لا يمكن تجاوز المخزون المتاح');return}cart.set(p.id,{...p,quantity:q+1});renderCart()}))}catch{grid.innerHTML='<article><span>تعذر تحميل المتجر من الخادم حاليًا.</span><button type="button" class="hl-store-retry">إعادة المحاولة</button></article>';grid.querySelector('.hl-store-retry')?.addEventListener('click',loadProducts)}};
  checkout.addEventListener('click',async()=>{if(!window.HydrolandAuth?.isAuthenticated?.()){toast('سجّل الدخول أولًا لإتمام الطلب');document.querySelector('.hl-login')?.classList.remove('hidden');return}checkout.disabled=true;try{const r=await window.HydrolandAuth.authorizedFetch('/store/orders',{method:'POST',body:JSON.stringify({items:[...cart.values()].map(x=>({productId:x.id,quantity:x.quantity}))})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(Array.isArray(body.message)?body.message.join('، '):body.message||'تعذر إنشاء الطلب');cart.clear();renderCart();toast('تم إنشاء الطلب بنجاح');await loadProducts()}catch(e){toast(e.message||'تعذر إنشاء الطلب')}finally{renderCart()}});
  panel.querySelector('.hl-store-orders').addEventListener('click',async()=>{if(!window.HydrolandAuth?.isAuthenticated?.()){toast('سجّل الدخول لعرض طلباتك');return}orders.hidden=false;orders.textContent='جارٍ تحميل الطلبات...';try{const r=await window.HydrolandAuth.authorizedFetch('/store/orders/mine');const data=await r.json();if(!r.ok||!Array.isArray(data))throw new Error();orders.innerHTML=data.length?data.map(o=>'<article><b>'+esc(o.status)+'</b><span>'+money(o.totalMinor,o.currency)+'</span><small>'+new Date(o.createdAt).toLocaleString('ar-SA')+'</small></article>').join(''):'لا توجد طلبات حتى الآن.'}catch{orders.textContent='تعذر تحميل الطلبات.'}});
  loadProducts();
})();