(() => {
  if (!document.querySelector('script[src="./hydroland-booking-admin.js"]')) {
    const module = document.createElement('script'); module.src = './hydroland-booking-admin.js'; module.defer = true; document.body.appendChild(module);
  }
  if (!document.querySelector('script[src="./hydroland-weather-admin.js"]')) {
    const module = document.createElement('script'); module.src = './hydroland-weather-admin.js'; module.defer = true; document.body.appendChild(module);
  }
  if (!document.querySelector('script[src="./hydroland-calendar-admin.js"]')) {
    const module = document.createElement('script'); module.src = './hydroland-calendar-admin.js'; module.defer = true; document.body.appendChild(module);
  }
  if (!document.querySelector('link[href="./hydroland-policy-admin.css"]')) {
    const link = document.createElement('link'); link.rel = 'stylesheet'; link.href = './hydroland-policy-admin.css'; document.head.appendChild(link);
  }
  if (!document.querySelector('script[src="./hydroland-policy-admin.js"]')) {
    const module = document.createElement('script'); module.src = './hydroland-policy-admin.js'; module.defer = true; document.body.appendChild(module);
  }

  const host = document.getElementById('role-console') || document.querySelector('main');
  if (!host) return;
  const box = document.createElement('section'); box.className = 'hl-admin'; box.hidden = true;
  box.innerHTML = `
    <div class="hl-admin__header"><div><span class="eyebrow">HYDROLAND / الإدارة</span><h2>مركز التحكم التشغيلي</h2><p>مراجعة الطلبات وإدارة الحسابات وسياسات التدقيق من بيانات المنصة الفعلية.</p></div><button class="btn btn-primary" type="button" data-admin-refresh>تحديث البيانات</button></div>
    <div class="hl-admin__metrics"><article><span>طلبات بانتظار المراجعة</span><strong data-admin-metric="pendingReviews">—</strong></article><article><span>حجوزات نشطة</span><strong data-admin-metric="activeBookings">—</strong></article><article><span>الحسابات المسجلة</span><strong data-admin-metric="accounts">—</strong></article><article><span>رحلات مفتوحة</span><strong data-admin-metric="openTrips">—</strong></article></div>
    <div class="hl-admin__grid"><article class="hl-admin__panel"><div class="hl-admin__panel-title"><h3>طابور المراجعة</h3><span data-admin-state>بانتظار الاتصال</span></div><div class="hl-admin__queue" data-admin-queue><p>سجّل الدخول بحساب إداري ثم حدّث البيانات لعرض الطلبات الفعلية.</p></div></article><article class="hl-admin__panel"><div class="hl-admin__panel-title"><h3>ضوابط الإدارة</h3><span>مفعل</span></div><ul><li>مركز سياسات التدقيق يتحكم في حالة كل شرط تشغيلي.</li><li>كل بند يمكن أن يكون مفعّلًا أو موقوفًا أو تحت المراجعة.</li><li>كل تغيير في السياسة يُسجل في سجل التدقيق.</li></ul></article><article class="hl-admin__panel hl-admin__credential-panel"><div class="hl-admin__panel-title"><h3>مراجعة الشهادات والمستندات</h3><span data-credential-review-state>بانتظار الاتصال</span></div><div class="hl-admin__queue" data-credential-review-list><p>لا توجد بيانات محملة.</p></div></article></div>
    <p class="hl-admin__notice" data-admin-copy>بيانات الإدارة تظهر عند اتصال المنصة بخادم HYDROLAND.</p>`;
  host.insertAdjacentElement('afterend', box);

  const style=document.createElement('style');style.textContent=`.hl-admin__credential-panel{grid-column:1/-1}.hl-admin__credential-card{display:grid;gap:.7rem;padding:.9rem;border:1px solid rgba(120,191,224,.18);border-radius:14px}.hl-admin__credential-card header{display:flex;justify-content:space-between;gap:1rem;align-items:start}.hl-admin__credential-card header small{display:block;color:#9fbccc;margin-top:.2rem}.hl-admin__credential-docs,.hl-admin__credential-actions,.hl-admin__credential-verify-actions{display:flex;gap:.45rem;flex-wrap:wrap}.hl-admin__credential-card button,.hl-admin__credential-card input,.hl-admin__credential-card select{border:1px solid rgba(120,191,224,.2);border-radius:10px;padding:.55rem .7rem;background:rgba(255,255,255,.045);color:#eaf7fb;font:inherit}.hl-admin__credential-card input,.hl-admin__credential-card select{min-width:min(260px,100%);flex:1}.hl-admin__credential-card button{font-weight:800}.hl-admin__credential-card button:disabled{opacity:.48;cursor:not-allowed}.hl-admin__credential-verification{display:grid;gap:.55rem;padding:.75rem;border:1px solid rgba(229,180,95,.24);border-radius:12px;background:rgba(229,180,95,.045)}.hl-admin__credential-verification-grid{display:grid;grid-template-columns:minmax(220px,.8fr) minmax(220px,1fr);gap:.55rem}.hl-admin__credential-verification label{display:grid;gap:.25rem;font-size:.85rem;font-weight:800}.hl-admin__credential-verification small{color:#aac3d1;line-height:1.6}.hl-admin__credential-verification .ready{color:#b8e8c8;font-weight:800}.hl-admin__credential-verification .required{color:#f3d496;font-weight:800}@media(max-width:760px){.hl-admin__credential-verification-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
  const getBase = () => (window.HydrolandAuth?.apiBase || window.HYDROLAND_API_BASE || 'http://localhost:3001/api/v1').replace(/\/$/, '');
  const setNotice = message => { const notice=box.querySelector('[data-admin-copy]'); if(notice) notice.textContent=message; };
  const renderQueue = items => { const queue=box.querySelector('[data-admin-queue]'); if(!queue)return; queue.textContent=''; if(!items.length){const empty=document.createElement('p');empty.textContent='لا توجد طلبات معلقة حالياً.';queue.appendChild(empty);return;} items.forEach(item=>{const name=item.account?.person?[item.account.person.firstName,item.account.person.lastName].filter(Boolean).join(' '):item.account?.email||'حساب جديد';const type=item.type==='ORGANIZATION'?'طلب جهة / منظمة':'طلب تفعيل حساب';const article=document.createElement('article');article.className='hl-admin__queue-item';const strong=document.createElement('strong');strong.textContent=name;const span=document.createElement('span');span.textContent=type;article.append(strong,span);queue.appendChild(article);}); };
  const api=async(path,options={})=>{const client=window.HydrolandAuth?.authorizedFetch;if(!client)throw new Error('AUTH_REQUIRED');const response=await client(path,options),body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.message||`HTTP_${response.status}`);return body};
  const toast=message=>{const t=document.getElementById('toast');if(!t)return;t.textContent=message;t.classList.add('visible');clearTimeout(window.__hlAdminCredentialToast);window.__hlAdminCredentialToast=setTimeout(()=>t.classList.remove('visible'),2400)};
  const reviewState={catalog:[]};
  const selectedCatalogEntry=select=>reviewState.catalog.find(item=>item.source===select.value)||reviewState.catalog[0]||null;

  function renderCredentialReviews(items){
    const list=box.querySelector('[data-credential-review-list]');if(!list)return;list.textContent='';
    if(!items.length){const empty=document.createElement('p');empty.textContent='لا توجد شهادات بانتظار المراجعة.';list.appendChild(empty);return}
    items.forEach(credential=>{
      const article=document.createElement('article');article.className='hl-admin__credential-card';article.dataset.credentialReview=credential.id;
      const header=document.createElement('header'),copy=document.createElement('div'),title=document.createElement('strong'),meta=document.createElement('small'),status=document.createElement('span');title.textContent=credential.title||'شهادة';const owner=[credential.person?.firstName,credential.person?.lastName].filter(Boolean).join(' ')||credential.person?.account?.email||'مستخدم';meta.textContent=`${credential.issuer||'جهة غير محددة'} · ${owner}`;status.textContent=credential.verificationStatus||'PENDING';copy.append(title,meta);header.append(copy,status);article.appendChild(header);
      const docs=document.createElement('div');docs.className='hl-admin__credential-docs';(credential.documents||[]).forEach(documentRow=>{const button=document.createElement('button');button.type='button';button.textContent=`عرض: ${documentRow.originalName||'المستند'}`;button.addEventListener('click',async()=>{button.disabled=true;try{const access=await api(`/credentials/admin/${encodeURIComponent(credential.id)}/documents/${encodeURIComponent(documentRow.id)}/access`);if(!access?.url)throw new Error('تعذر إنشاء رابط المستند');window.open(access.url,'_blank','noopener,noreferrer')}catch(error){toast(error?.message||'تعذر فتح المستند')}finally{button.disabled=false}});docs.appendChild(button)});if(!(credential.documents||[]).length){const empty=document.createElement('small');empty.textContent='لا يوجد مستند مرفق';docs.appendChild(empty)}article.appendChild(docs);

      const verification=document.createElement('section');verification.className='hl-admin__credential-verification';
      const verifyGrid=document.createElement('div');verifyGrid.className='hl-admin__credential-verification-grid';
      const sourceLabel=document.createElement('label');sourceLabel.textContent='جهة التحقق الرسمية';const source=document.createElement('select');source.setAttribute('aria-label','جهة التحقق الرسمية');reviewState.catalog.forEach(entry=>{const option=document.createElement('option');option.value=entry.source;option.textContent=`${entry.source} · ${entry.name}`;source.appendChild(option)});sourceLabel.appendChild(source);
      const referenceLabel=document.createElement('label');referenceLabel.textContent='رقم/مرجع التحقق';const reference=document.createElement('input');reference.placeholder='أدخل المرجع الظاهر في المصدر الرسمي';reference.setAttribute('aria-label','مرجع التحقق الرسمي');referenceLabel.appendChild(reference);verifyGrid.append(sourceLabel,referenceLabel);verification.appendChild(verifyGrid);
      const sourceNote=document.createElement('small'),evidenceState=document.createElement('small');const verifyActions=document.createElement('div');verifyActions.className='hl-admin__credential-verify-actions';const openOfficial=document.createElement('button');openOfficial.type='button';openOfficial.textContent='فتح التحقق الرسمي';const saveEvidence=document.createElement('button');saveEvidence.type='button';saveEvidence.textContent='حفظ دليل التحقق';verifyActions.append(openOfficial,saveEvidence);verification.append(sourceNote,verifyActions,evidenceState);article.appendChild(verification);

      const actions=document.createElement('div');actions.className='hl-admin__credential-actions';const reason=document.createElement('input');reason.placeholder='سبب الرفض (5 أحرف على الأقل)';reason.setAttribute('aria-label','سبب رفض الشهادة');const approve=document.createElement('button');approve.type='button';approve.textContent='اعتماد الشهادة';const reject=document.createElement('button');reject.type='button';reject.textContent='رفض الشهادة';actions.append(reason,approve,reject);article.appendChild(actions);

      const evidenceReady=()=>Boolean(credential.externalVerificationEvidenceRecordedAt);
      const syncEvidenceUi=()=>{const entry=selectedCatalogEntry(source);if(!entry){openOfficial.disabled=true;saveEvidence.disabled=true;approve.disabled=true;sourceNote.textContent='تعذر تحميل قائمة جهات التحقق الرسمية.';evidenceState.textContent='';return}openOfficial.disabled=false;saveEvidence.disabled=false;const professionalBoundary=entry.source!=='SWSDF'&&Array.isArray(entry.scope)&&entry.scope.includes('PROFESSIONAL')?' الشهادة الدولية لا تغني عن رخصة SWSDF للمحترف داخل السعودية.':'';sourceNote.textContent=`${entry.saudiEvidence||''}${professionalBoundary}`;approve.disabled=!evidenceReady();evidenceState.className=evidenceReady()?'ready':'required';evidenceState.textContent=evidenceReady()?`✓ دليل تحقق محفوظ${credential.externalVerificationEvidenceRecordedAt?` · ${new Date(credential.externalVerificationEvidenceRecordedAt).toLocaleString('ar-SA')}`:''}`:'يلزم حفظ دليل تحقق رسمي قبل الاعتماد.'};
      source.addEventListener('change',syncEvidenceUi);openOfficial.addEventListener('click',()=>{const entry=selectedCatalogEntry(source);if(entry?.verificationUrl)window.open(entry.verificationUrl,'_blank','noopener,noreferrer')});
      saveEvidence.addEventListener('click',async()=>{const entry=selectedCatalogEntry(source),value=reference.value.trim();if(!entry)return;if(value.length<3){toast('أدخل مرجع تحقق من 3 أحرف على الأقل');reference.focus();return}saveEvidence.disabled=true;try{const result=await api(`/credentials/admin/${encodeURIComponent(credential.id)}/external-verification-evidence`,{method:'POST',body:JSON.stringify({source:entry.source,method:entry.methods?.[0],reference:value,verificationUrl:entry.verificationUrl})});credential.externalVerificationEvidenceRecordedAt=result?.evidence?.checkedAt||new Date().toISOString();syncEvidenceUi();toast('تم حفظ دليل التحقق الرسمي')}catch(error){toast(error?.message||'تعذر حفظ دليل التحقق')}finally{saveEvidence.disabled=false}});
      const decide=async(outcome)=>{const rejectionReason=reason.value.trim();if(outcome==='VERIFIED'&&!evidenceReady()){toast('احفظ دليل التحقق الرسمي قبل اعتماد الشهادة');return}if(outcome==='REJECTED'&&rejectionReason.length<5){toast('اكتب سبب رفض من 5 أحرف على الأقل');reason.focus();return}approve.disabled=true;reject.disabled=true;try{await api(`/credentials/admin/${encodeURIComponent(credential.id)}/decision`,{method:'POST',body:JSON.stringify({outcome,...(outcome==='REJECTED'?{reason:rejectionReason}:{})})});toast(outcome==='VERIFIED'?'تم اعتماد الشهادة':'تم رفض الشهادة');await refreshCredentialReviews()}catch(error){toast(error?.message||'تعذر تحديث الشهادة')}finally{reject.disabled=false;if(outcome!=='VERIFIED')syncEvidenceUi()}};
      approve.addEventListener('click',()=>void decide('VERIFIED'));reject.addEventListener('click',()=>void decide('REJECTED'));syncEvidenceUi();list.appendChild(article);
    });
  }

  async function refreshCredentialReviews(){const state=box.querySelector('[data-credential-review-state]');if(!window.HydrolandAuth?.isAuthenticated?.()){if(state)state.textContent='يتطلب دخول إداري';renderCredentialReviews([]);return}if(state)state.textContent='جارٍ التحديث';try{const [rows,catalog]=await Promise.all([api('/credentials/admin/pending'),api('/credentials/verification-organizations')]);reviewState.catalog=Array.isArray(catalog)?catalog:[];renderCredentialReviews(Array.isArray(rows)?rows:[]);if(state)state.textContent='متصل بالخادم'}catch(error){reviewState.catalog=[];if(state)state.textContent=error?.message==='AUTH_REQUIRED'?'يتطلب دخول إداري':'تعذر التحميل';renderCredentialReviews([])}}

  async function refreshAdminOverview(){const token=window.HydrolandAuth?.getAccessToken?.();const state=box.querySelector('[data-admin-state]');if(!token){if(state)state.textContent='يتطلب دخول إداري';setNotice('سجّل الدخول بحساب إداري لعرض البيانات الفعلية.');await refreshCredentialReviews();return;}if(state)state.textContent='جارٍ التحديث';try{const headers={Authorization:'Bearer '+token};const overviewResponse=await fetch(getBase()+'/admin/overview',{headers});if(!overviewResponse.ok)throw new Error('overview unavailable');const overview=await overviewResponse.json();Object.keys(overview).forEach(key=>{const metric=box.querySelector('[data-admin-metric="'+key+'"]');if(metric)metric.textContent=String(overview[key]);});const queueResponse=await fetch(getBase()+'/admin/review-queue',{headers});if(queueResponse.ok)renderQueue(await queueResponse.json());if(state)state.textContent='متصل بالخادم';setNotice('تم تحديث بيانات الإدارة من خادم HYDROLAND.');window.HydrolandOperationsCalendar?.reload?.();window.HydrolandPolicyAdmin?.reload?.();}catch(_){if(state)state.textContent='تعذر الاتصال';setNotice('تعذر الوصول لخادم الإدارة. تأكد من تشغيل واجهة API وتسجيل الدخول بحساب إداري.');}finally{await refreshCredentialReviews()}}
  const show=()=>{box.hidden=false;refreshAdminOverview();};const hide=()=>{box.hidden=true;};
  document.addEventListener('hydroland:role-changed',event=>{if(event.detail?.role==='admin')show();else hide();});
  document.addEventListener('hydroland:auth-changed',()=>{if(!box.hidden)refreshAdminOverview();});
  box.querySelector('[data-admin-refresh]')?.addEventListener('click',refreshAdminOverview);
})();
