-- Candidate-only additive constraints from read-only production metadata.
-- No historical migration edits or production adoption authorization.
ALTER TABLE "AdministrativeRecord" ADD CONSTRAINT "AdministrativeRecord_license_dates_check" CHECK ("licenseAssetId" IS NULL AND "licenseIssuedAt" IS NULL AND "licenseExpiresAt" IS NULL OR "licenseAssetId" IS NOT NULL AND "licenseIssuedAt" IS NOT NULL AND "licenseExpiresAt" IS NOT NULL AND "licenseExpiresAt" > "licenseIssuedAt");
ALTER TABLE "AdministrativeRecord" ADD CONSTRAINT "AdministrativeRecord_license_review_check" CHECK ("licenseReviewStatus" IS NULL AND "licenseReviewSubmittedAt" IS NULL AND "licenseReviewSubmittedById" IS NULL AND "licenseReviewDecidedAt" IS NULL AND "licenseReviewDecidedById" IS NULL AND "licenseReviewReason" IS NULL OR "licenseReviewStatus" IS NOT NULL AND ("licenseReviewStatus" = ANY (ARRAY['PENDING'::text, 'APPROVED'::text, 'REJECTED'::text])) AND "licenseReviewSubmittedAt" IS NOT NULL AND "licenseReviewSubmittedById" IS NOT NULL AND ("licenseReviewStatus" = 'PENDING'::text AND "licenseReviewDecidedAt" IS NULL AND "licenseReviewDecidedById" IS NULL AND "licenseReviewReason" IS NULL OR ("licenseReviewStatus" = ANY (ARRAY['APPROVED'::text, 'REJECTED'::text])) AND "licenseReviewDecidedAt" IS NOT NULL AND "licenseReviewDecidedById" IS NOT NULL AND "licenseReviewDecidedById" <> "licenseReviewSubmittedById" AND ("licenseReviewStatus" = 'APPROVED'::text OR "licenseReviewReason" IS NOT NULL AND length(TRIM(BOTH FROM "licenseReviewReason")) >= 5)));
ALTER TABLE "BoatResourceCompliance" ADD CONSTRAINT "BoatResourceCompliance_resourceId_fkey" FOREIGN KEY ("resourceId") REFERENCES "CalendarResource"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_seats_check" CHECK (seats > 0);
ALTER TABLE "FinanceAccountantShift" ADD CONSTRAINT "FinanceAccountantShift_accountantAccountId_fkey" FOREIGN KEY ("accountantAccountId") REFERENCES "Account"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "FinanceAccountantShift" ADD CONSTRAINT "FinanceAccountantShift_centerOrgUnitId_fkey" FOREIGN KEY ("centerOrgUnitId") REFERENCES "Organization"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "FinanceAccountantShift" ADD CONSTRAINT "FinanceAccountantShift_openingBalance_nonnegative" CHECK ("openingBalanceMinor" >= 0);
ALTER TABLE "FinanceAccountantShift" ADD CONSTRAINT "FinanceAccountantShift_reviewedByAccountId_fkey" FOREIGN KEY ("reviewedByAccountId") REFERENCES "Account"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "FinanceEntry" ADD CONSTRAINT "FinanceEntry_postedByAccountId_fkey" FOREIGN KEY ("postedByAccountId") REFERENCES "Account"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "FinanceShiftEntry" ADD CONSTRAINT "FinanceShiftEntry_amount_positive" CHECK ("amountMinor" > 0);
ALTER TABLE "FinanceShiftEntry" ADD CONSTRAINT "FinanceShiftEntry_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "FinanceShiftEntry" ADD CONSTRAINT "FinanceShiftEntry_recordedByAccountId_fkey" FOREIGN KEY ("recordedByAccountId") REFERENCES "Account"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "FinanceShiftHandover" ADD CONSTRAINT "FinanceShiftHandover_actualCash_nonnegative" CHECK ("actualCashMinor" IS NULL OR "actualCashMinor" >= 0);
ALTER TABLE "FinanceShiftHandover" ADD CONSTRAINT "FinanceShiftHandover_expectedCash_nonnegative" CHECK ("expectedCashMinor" >= 0);
ALTER TABLE "FinanceShiftHandover" ADD CONSTRAINT "FinanceShiftHandover_fromAccountantId_fkey" FOREIGN KEY ("fromAccountantId") REFERENCES "Account"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "FinanceShiftHandover" ADD CONSTRAINT "FinanceShiftHandover_toAccountantId_fkey" FOREIGN KEY ("toAccountantId") REFERENCES "Account"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "InstructorEarning" ADD CONSTRAINT "InstructorEarning_amount_positive" CHECK ("amountMinor" > 0);
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_amountMinor_check" CHECK ("amountMinor" > 0);
ALTER TABLE "Receivable" ADD CONSTRAINT "Receivable_amounts_check" CHECK ("totalMinor" > 0 AND "paidMinor" >= 0 AND "outstandingMinor" >= 0 AND ("paidMinor" + "outstandingMinor") = "totalMinor");
ALTER TABLE "Receivable" ADD CONSTRAINT "Receivable_centerOrgUnitId_fkey" FOREIGN KEY ("centerOrgUnitId") REFERENCES "OrgUnit"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "Receivable" ADD CONSTRAINT "Receivable_customerAccountId_fkey" FOREIGN KEY ("customerAccountId") REFERENCES "Account"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "Receivable" ADD CONSTRAINT "Receivable_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "ReceivableInstallment" ADD CONSTRAINT "ReceivableInstallment_amounts_check" CHECK ("amountMinor" > 0 AND "paidMinor" >= 0 AND "paidMinor" <= "amountMinor");
ALTER TABLE "ReceivablePayment" ADD CONSTRAINT "ReceivablePayment_amount_check" CHECK ("amountMinor" > 0);
ALTER TABLE "ReceivablePayment" ADD CONSTRAINT "ReceivablePayment_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "RewardAccount" ADD CONSTRAINT "RewardAccount_points_nonnegative" CHECK (points >= 0);
ALTER TABLE "RewardEntry" ADD CONSTRAINT "RewardEntry_balanceAfter_nonnegative" CHECK ("balanceAfter" >= 0);
ALTER TABLE "RewardEntry" ADD CONSTRAINT "RewardEntry_points_positive" CHECK (points > 0);
ALTER TABLE "SafetyIncident" ADD CONSTRAINT "SafetyIncident_description_length_check" CHECK (char_length(btrim(description)) >= 3 AND char_length(btrim(description)) <= 5000);
ALTER TABLE "SafetyIncident" ADD CONSTRAINT "SafetyIncident_location_length_check" CHECK ("locationName" IS NULL OR char_length(btrim("locationName")) <= 160);
ALTER TABLE "SafetyIncident" ADD CONSTRAINT "SafetyIncident_title_length_check" CHECK (char_length(btrim(title)) >= 3 AND char_length(btrim(title)) <= 160);
ALTER TABLE "ThemeSchedule" ADD CONSTRAINT "ThemeSchedule_valid_status" CHECK (status = ANY (ARRAY['DRAFT'::text, 'PUBLISHED'::text, 'ARCHIVED'::text]));
ALTER TABLE "ThemeSchedule" ADD CONSTRAINT "ThemeSchedule_valid_window" CHECK ("endsAt" > "startsAt");
ALTER TABLE "Trip" ADD CONSTRAINT "Trip_capacity_check" CHECK (capacity > 0);
ALTER TABLE "TripComplianceReview" ADD CONSTRAINT "TripComplianceReview_reviewedByAccountId_fkey" FOREIGN KEY ("reviewedByAccountId") REFERENCES "Account"(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "TripComplianceReview" ADD CONSTRAINT "TripComplianceReview_tripId_fkey" FOREIGN KEY ("tripId") REFERENCES "Trip"(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "Wallet" ADD CONSTRAINT "Wallet_balanceMinor_nonnegative" CHECK ("balanceMinor" >= 0);
ALTER TABLE "WalletEntry" ADD CONSTRAINT "WalletEntry_amountMinor_positive" CHECK ("amountMinor" > 0);
ALTER TABLE "WalletEntry" ADD CONSTRAINT "WalletEntry_balanceAfterMinor_nonnegative" CHECK ("balanceAfterMinor" >= 0);
