import {test,expect} from '@playwright/test';
import {openWorkspaceSwitcher} from './portal-test-helpers.js';
const json=(route,body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
const booking={id:'booking-one',tripId:'trip-one',customerName:'عميل المركز',status:'PENDING',seats:2,createdAt:'2030-01-01T06:00:00Z',updatedAt:'2030-01-01T06:00:00Z',trip:{id:'trip-one',title:'رحلة عالم الغوص',status:'OPEN',capacity:6,startsAt:'2030-01-02T07:00:00Z'}};
const listing=(items=[booking],extra={})=>({items,total:items.length,page:1,pageSize:20,totalPages:1,counts:[{status:'PENDING',count:1,seats:2}],...extra});
const details=(extra={})=>({booking:{...booking},stateToken:'a'.repeat(64),participants:[{id:'p1',fullName:'مشارك الحجز',eligibilityStatus:'ELIGIBLE',certificationTitle:'غواص مياه مفتوحة'}],financial:[{status:'CAPTURED',currency:'SAR',amountMinor:20000,count:1}],requiredAmountMinor:20000,paymentSatisfied:true,confirmedSeats:0,remainingSeats:6,blockers:[],policyReview:{required:false,issues:[]},actions:['CONFIRM','CANCEL'],lastAction:null,...extra});
const listRoute=/\/api\/v1\/center\/me\/bookings(?:\?.*)?$/;
const detailRoute=/\/api\/v1\/center\/me\/bookings\/booking-one$/;
async function install(page){
 const state={active:true,reads:[],posts:[],data:details(),list:listing()};
 const profile={id:'center-bookings-review',email:'center-bookings@example.invalid',status:'ACTIVE',person:{firstName:'مدير',lastName:'المركز'},roleAssignments:[{role:'DIVE_CENTER',status:'ACTIVE'}]};
 await page.route('**/api/v1/**',route=>{const path=new URL(route.request().url()).pathname;if(path==='/api/v1/me')return json(route,{...profile,roleAssignments:state.active?profile.roleAssignments:[]});return json(route,[])});
 await page.route('**/api/v1/auth/google/config',route=>json(route,{enabled:false}));await page.route(/\/api\/v1\/me\/diver-profile$/,route=>json(route,{profile:null,equipment:[]}));await page.route('**/api/v1/center/me/overview',route=>json(route,{center:{displayName:'عالم الغوص'},metrics:{newBookings:1,tripsToday:1,activeMembers:1,totalTrips:1}}));
 await page.route(listRoute,route=>{state.reads.push(new URL(route.request().url()).searchParams);return json(route,state.list)});await page.route(detailRoute,route=>json(route,state.data));
 await page.route('**/api/v1/center/me/bookings/booking-one/actions',route=>{const body=route.request().postDataJSON();state.posts.push(body);state.data=details({booking:{...booking,status:body.action==='CONFIRM'?'CONFIRMED':'CANCELLED'},actions:body.action==='CONFIRM'?['CANCEL']:[],stateToken:'b'.repeat(64)});state.list=listing([state.data.booking]);return json(route,{id:booking.id,status:state.data.booking.status,financialActionExecuted:false},201)});
 await page.goto('/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>Boolean(window.HydrolandAuth&&window.HydrolandProfile&&window.HydrolandCenterBookings));await page.evaluate(async()=>{window.HydrolandAuth.acceptSession({accessToken:'booking-access',refreshToken:'booking-refresh'},window.HydrolandAuth.beginAuthAttempt());await window.HydrolandProfile.load()});await openWorkspaceSwitcher(page);await page.locator('#role-dialog [data-role="center"]').click();await page.locator('[data-portal-label="إدارة الحجوزات"]').click();await expect(page.locator('#hl-center-bookings')).toBeVisible();return state;
}
const panel=page=>page.locator('#hl-center-bookings');
const openDetail=async page=>{await panel(page).getByRole('button',{name:'تفاصيل الحجز',exact:true}).first().click();await expect(panel(page).locator('[data-booking-detail]')).toContainText('مشارك الحجز')};

test('booking sidebar opens a separate scoped searchable paginated directory',async({page})=>{
 const state=await install(page);expect(await panel(page).evaluate(el=>el.getBoundingClientRect().top>=document.querySelector('.hl-service-heading').getBoundingClientRect().bottom)).toBe(true);await expect(panel(page)).toContainText('رحلة عالم الغوص');await expect(panel(page).locator('[data-center-trip-edit]')).toHaveCount(0);
 state.list=listing([booking],{total:21,totalPages:2});await panel(page).getByLabel('العميل أو الرحلة أو رقم الحجز').fill('عالم الغوص');await panel(page).getByLabel('حالة الحجز',{exact:true}).selectOption('PENDING');await panel(page).getByRole('button',{name:'بحث',exact:true}).click();await expect.poll(()=>state.reads.at(-1)?.get('q')).toBe('عالم الغوص');expect(state.reads.at(-1).get('status')).toBe('PENDING');
 state.list=listing([{...booking,id:'booking-two'}],{page:2,total:21,totalPages:2});await panel(page).getByRole('button',{name:'التالي',exact:true}).click();await expect.poll(()=>state.reads.at(-1)?.get('page')).toBe('2');await expect(panel(page)).toContainText('صفحة 2 من 2');
 state.list=listing();await panel(page).getByRole('button',{name:'مسح البحث'}).click();await expect.poll(()=>state.reads.at(-1)?.get('page')).toBe('1');expect(state.reads.at(-1).get('q')).toBe('');expect(state.reads.at(-1).get('status')).toBe('ALL');
});
test('detail shows blockers and safely renders participant names without approval controls',async({page})=>{
 const state=await install(page);state.data=details({participants:[{fullName:'<img src=x onerror="window.bookingXss=1">',eligibilityStatus:'PENDING'}],actions:['CANCEL'],blockers:['PAYMENT_REQUIRED','PARTICIPANT_ELIGIBILITY_PENDING'],paymentSatisfied:false});await panel(page).getByRole('button',{name:'تفاصيل الحجز'}).click();const box=panel(page).locator('[data-booking-detail]');await expect(box).toContainText('لم يكتمل دفع المبلغ');await expect(box).toContainText('أهلية المشاركين تحتاج مراجعة');await expect(box).toContainText('<img src=x');await expect(box.locator('img')).toHaveCount(0);await expect(box.getByRole('button',{name:'تأكيد الحجز',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>window.bookingXss)).toBeUndefined();
});
test('confirmation sends the displayed revision once and refreshes saved status',async({page})=>{
 const state=await install(page);await openDetail(page);await panel(page).getByRole('button',{name:'تأكيد الحجز',exact:true}).click();await expect.poll(()=>state.posts.length).toBe(1);expect(state.posts[0]).toMatchObject({action:'CONFIRM',expectedState:'a'.repeat(64)});expect(state.posts[0].requestId).toMatch(/^[a-f0-9-]{36}$/);expect(state.posts[0]).not.toHaveProperty('accountId');await expect(panel(page)).toContainText('تم تأكيد الحجز.');await expect(panel(page).getByRole('button',{name:'تأكيد الحجز',exact:true})).toHaveCount(0);await expect(panel(page).locator('[data-booking-detail]')).toContainText('مؤكد');
});
test('cancellation requires a reason and financial acknowledgement',async({page})=>{
 const state=await install(page);await openDetail(page);const form=panel(page).locator('[data-booking-action="CANCEL"]');await form.getByRole('button',{name:'حفظ إلغاء الحجز'}).click();expect(state.posts.length).toBe(0);await form.getByLabel('سبب الإلغاء').fill('إلغاء بناء على طلب العميل');await form.getByRole('checkbox').check();await form.getByRole('button',{name:'حفظ إلغاء الحجز'}).click();await expect.poll(()=>state.posts.length).toBe(1);expect(state.posts[0]).toMatchObject({action:'CANCEL',reason:'إلغاء بناء على طلب العميل',financialAcknowledged:true});expect(state.posts[0]).not.toHaveProperty('amountMinor');await expect(panel(page)).toContainText('تم حفظ إلغاء الحجز');await expect(panel(page).locator('[data-booking-detail]')).toContainText('لا توجد إجراءات متاحة');
});
test('lost response retries the same request; stale confirmation requires fresh details',async({page})=>{
 await install(page);const posts=[];let failure=500;await page.route('**/api/v1/center/me/bookings/booking-one/actions',route=>{posts.push(route.request().postDataJSON());return json(route,{message:failure===500?'تعذر حفظ الإجراء':'تغيرت بيانات الحجز'},failure)});await openDetail(page);let button=panel(page).getByRole('button',{name:'تأكيد الحجز',exact:true});await button.click();await expect(panel(page)).toContainText('تعذر حفظ الإجراء');await button.click();await expect.poll(()=>posts.length).toBe(2);expect(posts[0].requestId).toBe(posts[1].requestId);
 failure=409;await button.click();await expect(button).toBeDisabled();await expect(panel(page)).toContainText('تغيرت بيانات الحجز');await panel(page).getByRole('button',{name:'تحديث التفاصيل',exact:true}).first().click();await expect(button).toBeEnabled();await button.click();await expect.poll(()=>posts.length).toBe(4);expect(posts[3].requestId).not.toBe(posts[0].requestId);
});
test('revoked center role stops mutation and removes identities',async({page})=>{
 const state=await install(page);await openDetail(page);state.active=false;await panel(page).getByRole('button',{name:'تأكيد الحجز',exact:true}).click();await expect(panel(page)).toHaveCount(0);expect(state.posts.length).toBe(0);await expect(page.getByText('مشارك الحجز')).toHaveCount(0);
});
test('late detail after logout cannot restore identities',async({page})=>{
 await install(page);let release;const pending=new Promise(resolve=>{release=resolve});let started=false;await page.route(detailRoute,async route=>{started=true;await pending;await json(route,details()).catch(()=>{})});await panel(page).getByRole('button',{name:'تفاصيل الحجز'}).click();await expect.poll(()=>started).toBe(true);await page.evaluate(()=>window.HydrolandAuth.terminateSession());release();await expect(panel(page)).toHaveCount(0);await expect(page.getByText('مشارك الحجز')).toHaveCount(0);
});
test('directory and detail errors clear previous records and can retry',async({page})=>{
 const state=await install(page);await page.route(detailRoute,route=>json(route,{message:'Missing'},404));await panel(page).getByRole('button',{name:'تفاصيل الحجز'}).click();await expect(panel(page)).toContainText('الحجز غير موجود ضمن المركز');await page.route(detailRoute,route=>json(route,details()));await panel(page).getByRole('button',{name:'إعادة تحميل التفاصيل'}).click();await expect(panel(page)).toContainText('مشارك الحجز');
 await page.route(listRoute,route=>json(route,{bad:true}));await panel(page).getByRole('button',{name:'تحديث القائمة'}).click();await expect(panel(page)).toContainText('استجابة الحجوزات غير مكتملة');await expect(panel(page)).not.toContainText('مشارك الحجز');await page.route(listRoute,route=>json(route,listing([])));await panel(page).getByRole('button',{name:'إعادة المحاولة',exact:true}).click();await expect(panel(page)).toContainText('لا توجد حجوزات مطابقة');expect(state.posts.length).toBe(0);
});
test('review policy acknowledgement accompanies confirmation',async({page})=>{
 const state=await install(page);state.data=details({policyReview:{required:true,issues:['PAYMENT_REQUIRED']}});await openDetail(page);const form=panel(page).locator('[data-booking-action="CONFIRM"]');await form.getByRole('button',{name:'تأكيد الحجز'}).click();expect(state.posts.length).toBe(0);await form.getByRole('checkbox').check();await form.getByRole('button',{name:'تأكيد الحجز'}).click();await expect.poll(()=>state.posts.length).toBe(1);expect(state.posts[0].policyReviewAcknowledged).toBe(true);
});


test('booking detail reports canonical calendar reservation and refreshes changed health',async({page})=>{
 const state=await install(page);state.data=details({calendarReservation:{status:'RESERVED',issues:[],activeAllocationCount:2,confirmationGateEnforced:false}});await openDetail(page);const box=panel(page).locator('[data-booking-detail]');await expect(box).toContainText('موارد الرحلة محجوزة في موعدها');await expect(box).toContainText('2 تخصيص نشط');
 state.data=details({calendarReservation:{status:'NEEDS_ATTENTION',issues:['CALENDAR_RESOURCE_INACTIVE','CALENDAR_RESOURCE_CONFLICT'],activeAllocationCount:2,confirmationGateEnforced:false}});await box.getByRole('button',{name:'تحديث التفاصيل'}).click();await expect(box).toContainText('حجز موارد الرحلة يحتاج مراجعة');await expect(box).toContainText('أحد موارد الرحلة غير نشط');await expect(box).toContainText('يوجد تعارض في حجز مورد للرحلة');await expect(box.getByRole('button',{name:'تأكيد الحجز',exact:true})).toBeEnabled();expect(state.posts).toHaveLength(0);
});
