import {test,expect} from '@playwright/test';
import {openWorkspaceSwitcher} from './portal-test-helpers.js';
const json=(route,body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
const receivable={id:'ar-a',invoiceNumber:'INV-100',customerName:'عميل المركز',totalMinor:10000,paidMinor:0,outstandingMinor:10000,currency:'SAR',dueAt:'2030-02-01T20:59:59Z',status:'OPEN'};
const detail=()=>({centerOrgUnitId:'center-a',receivable:{...receivable},installments:[{id:'i1',sequence:1,amountMinor:4000,paidMinor:0,dueAt:'2030-01-01',status:'PENDING'},{id:'i2',sequence:2,amountMinor:6000,paidMinor:0,dueAt:'2030-02-01',status:'PENDING'}],collectable:true,collectionShiftId:'shift-a',collections:[],payments:{page:1,pageSize:25,total:2,items:[{id:'p1',amountMinor:4000,createdAt:'2030-01-01',providerReference:'PAY-40'},{id:'p2',amountMinor:6000,createdAt:'2030-01-02',providerReference:'PAY-60'}]}});
async function setup(page){
 const state={active:true,status:200,centers:[{id:'center-a',name:'الفرع الرئيسي',organizationName:'عالم الغوص'}],list:{centerOrgUnitId:'center-a',items:[{...receivable}],page:1,pageSize:25,total:1},invoices:{centerOrgUnitId:'center-a',items:[{id:'invoice-new',number:'INV-200',customerAccountId:'customer-a',customerName:'عميل المركز',totalMinor:10000,paymentStatus:'CREATED'}],page:1,pageSize:25,total:1},detail:detail(),reads:[],writes:[]};
 const profile={id:'ar-accountant',email:'ar@example.invalid',status:'ACTIVE',person:{firstName:'محاسب',lastName:'المركز'},roleAssignments:[{role:'DIVE_CENTER',status:'ACTIVE'}]};
 await page.route('**/api/v1/**',route=>json(route,[]));await page.route('**/api/v1/auth/google/config',route=>json(route,{enabled:false}));await page.route(/\/api\/v1\/me$/,route=>json(route,{...profile,roleAssignments:state.active?profile.roleAssignments:[]}));await page.route(/\/api\/v1\/me\/diver-profile$/,route=>json(route,{profile:null,equipment:[]}));
 await page.route('**/api/v1/center/me/overview',route=>json(route,{center:{displayName:'عالم الغوص'},metrics:{newBookings:0,tripsToday:0,activeMembers:1,totalTrips:0}}));
 await page.route('**/api/v1/finance/mine/centers',route=>json(route,state.centers));
 await page.route(/\/finance\/centers\/[^/]+\/receivables\/workspace(?:\?|$)/,route=>{const url=new URL(route.request().url());state.reads.push(url.pathname+url.search);return json(route,state.status===200?{...state.list,page:Number(url.searchParams.get('page')||1)}:{message:'Unavailable'},state.status)});
 await page.route(/\/finance\/centers\/[^/]+\/receivable-invoices(?:\?|$)/,route=>{state.reads.push(route.request().url());return json(route,state.invoices)});
 await page.route(/\/finance\/centers\/[^/]+\/receivables\/(?!workspace)[^/?]+(?:\?|$)/,route=>{state.reads.push(route.request().url());return json(route,state.status===200?state.detail:{message:'Unavailable'},state.status)});
 await page.route(/\/api\/v1\/finance\/receivables(?:\/[^/]+\/collections)?$/,route=>{state.writes.push({path:new URL(route.request().url()).pathname,body:route.request().postDataJSON()});return json(route,{receivableId:'ar-a',outstandingMinor:state.detail.receivable.outstandingMinor},201)});
 await page.goto('/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>Boolean(window.HydrolandCenterReceivables&&window.HydrolandProfile&&window.HydrolandAuth));await page.evaluate(async()=>{window.HydrolandAuth.acceptSession({accessToken:'ar-access',refreshToken:'ar-refresh'},window.HydrolandAuth.beginAuthAttempt());await window.HydrolandProfile.load()});await openWorkspaceSwitcher(page);await page.locator('#role-dialog [data-role="center"]').click();return state;
}
async function open(page){await page.locator('[data-portal-label="الذمم والتحصيل"]').click();const panel=page.locator('#hl-center-receivables');await expect(panel.locator('[data-ar-result]')).toHaveAttribute('aria-busy','false');return panel}
async function openDetail(panel){await panel.getByRole('button',{name:'عرض وتحصيل'}).click();await expect(panel.locator('[name=payment]')).toBeVisible()}
test('center receivables display scoped balance and responsive details',async({page})=>{
 const state=await setup(page),panel=await open(page);await expect(panel).toContainText('INV-100');await expect(panel).toContainText('100.00 ر.س.');expect(state.reads.at(-1)).toContain('/centers/center-a/receivables/workspace');await openDetail(panel);await expect(panel).toContainText('جدول الأقساط');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath('portal-center-receivables.png'),fullPage:true});
});
test('creates receivable using selected invoice and validates exact installment sum',async({page})=>{
 const state=await setup(page),panel=await open(page);await panel.getByRole('button',{name:'إنشاء ذمة من فاتورة'}).click();await panel.locator('[name=invoice]').selectOption('invoice-new');await panel.locator('[name=dueAt]').fill('2030-02-01');await panel.getByRole('button',{name:'إضافة قسط'}).click();await panel.getByRole('button',{name:'إضافة قسط'}).click();await panel.locator('[name=installmentAmount]').nth(0).fill('٤٠');await panel.locator('[name=installmentAmount]').nth(1).fill('50');await panel.locator('[name=installmentDue]').nth(0).fill('2030-01-01');await panel.locator('[name=installmentDue]').nth(1).fill('2030-02-01');await panel.getByRole('button',{name:'تسجيل الذمة',exact:true}).click();await expect(panel.locator('[data-ar-form-error]')).toContainText('مجموعها يساوي');expect(state.writes).toHaveLength(0);
 await panel.locator('[name=installmentAmount]').nth(1).fill('60');await panel.getByRole('button',{name:'تسجيل الذمة',exact:true}).click();await expect.poll(()=>state.writes.length).toBe(1);expect(state.writes[0].body).toEqual({centerOrgUnitId:'center-a',invoiceId:'invoice-new',customerAccountId:'customer-a',totalMinor:10000,paidMinor:0,dueAt:'2030-02-01T23:59:59+03:00',installments:[{sequence:1,amountMinor:4000,dueAt:'2030-01-01T23:59:59+03:00'},{sequence:2,amountMinor:6000,dueAt:'2030-02-01T23:59:59+03:00'}]});await expect(panel.locator('[role=status]')).toContainText('تم تسجيل الذمة');
});
test('collection records captured payment against selected installment and reloads receipt evidence',async({page})=>{
 const state=await setup(page),panel=await open(page);await openDetail(panel);await panel.locator('[name=payment]').selectOption('p1');await panel.locator('[name=installment]').selectOption('i1');await panel.locator('[name=receiptNumber]').fill('RCPT-40');state.detail={...detail(),receivable:{...receivable,paidMinor:4000,outstandingMinor:6000,status:'PARTIALLY_PAID'},collections:[{id:'collection-1',receiptNumber:'RCPT-40',amountMinor:4000,installmentSequence:1,shiftId:'shift-a',collectedByAccountId:'ar-accountant',collectedAt:'2030-01-01'}]};
 await panel.getByRole('button',{name:'تسجيل التحصيل',exact:true}).click();await expect.poll(()=>state.writes.length).toBe(1);expect(state.writes[0]).toEqual({path:'/api/v1/finance/receivables/ar-a/collections',body:{paymentId:'p1',amountMinor:4000,receiptNumber:'RCPT-40',installmentId:'i1'}});await expect(panel).toContainText('RCPT-40');await expect(panel).toContainText('shift-a');await expect(panel).toContainText('مسددة جزئيًا');
});
test('collection rejects payment exceeding selected installment before POST',async({page})=>{
 const state=await setup(page),panel=await open(page);await openDetail(panel);await panel.locator('[name=payment]').selectOption('p2');await panel.locator('[name=installment]').selectOption('i1');await panel.locator('[name=receiptNumber]').fill('RCPT-WRONG');await panel.getByRole('button',{name:'تسجيل التحصيل',exact:true}).click();await expect(panel.locator('[data-ar-form-error]')).toContainText('يغطي رصيده');expect(state.writes).toHaveLength(0);
});
test('list pagination and paid filter preserve center scope',async({page})=>{
 const state=await setup(page);state.list.total=26;const panel=await open(page);await panel.getByRole('button',{name:'التالي',exact:true}).click();await expect.poll(()=>state.reads.at(-1)).toContain('page=2&status=open');await panel.locator('[name=status]').selectOption('all');await expect.poll(()=>state.reads.at(-1)).toContain('page=1&status=all');
});
test('no accountant employment or eligible invoices exposes no financial write form',async({page})=>{
 const state=await setup(page);state.centers=[];let panel=await open(page);await expect(panel).toContainText('لا يوجد تعيين محاسب');await expect(panel.locator('form')).toHaveCount(0);state.centers=[{id:'center-a',name:'الفرع',organizationName:'المركز'}];state.invoices.items=[];await panel.getByRole('button',{name:'تحديث البيانات'}).click();await expect(panel).toContainText('INV-100');await panel.getByRole('button',{name:'إنشاء ذمة من فاتورة'}).click();await expect(panel).toContainText('لا توجد فواتير مؤهلة');await expect(panel.locator('form')).toHaveCount(0);
});
test('failed financial refresh clears previous customer data and retry recovers',async({page})=>{
 const state=await setup(page),panel=await open(page);state.status=503;await panel.getByRole('button',{name:'تحديث البيانات'}).click();await expect(panel.locator('[role=alert]')).toContainText('تعذر');await expect(panel).not.toContainText('عميل المركز');state.status=200;await panel.getByRole('button',{name:'تحديث البيانات'}).click();await expect(panel).toContainText('INV-100');
});
test('revoked role blocks collection and clears the workspace',async({page})=>{
 const state=await setup(page),panel=await open(page);await openDetail(panel);await panel.locator('[name=payment]').selectOption('p1');await panel.locator('[name=installment]').selectOption('i1');await panel.locator('[name=receiptNumber]').fill('RCPT-DENIED');state.active=false;await panel.getByRole('button',{name:'تسجيل التحصيل',exact:true}).click();await expect(panel).toHaveCount(0);expect(state.writes).toHaveLength(0);
});
test('late invoice response cannot repopulate a signed-out session',async({page})=>{
 await setup(page);const panel=await open(page);let pending;await page.route(/\/finance\/centers\/[^/]+\/receivable-invoices(?:\?|$)/,route=>{pending=route});await panel.getByRole('button',{name:'إنشاء ذمة من فاتورة'}).click();await expect.poll(()=>Boolean(pending)).toBe(true);await page.evaluate(()=>window.HydrolandAuth.terminateSession());await json(pending,{centerOrgUnitId:'center-a',items:[{id:'private-invoice',number:'فاتورة خاصة'}],page:1,pageSize:25,total:1});await expect(panel).toHaveCount(0);
});
test('pending collection disables duplicate submit and late result cannot restore logged-out data',async({page})=>{
 const state=await setup(page),panel=await open(page);await openDetail(panel);await panel.locator('[name=payment]').selectOption('p1');await panel.locator('[name=installment]').selectOption('i1');await panel.locator('[name=receiptNumber]').fill('RCPT-ONCE');let pending;await page.route('**/api/v1/finance/receivables/ar-a/collections',route=>{state.writes.push(route.request().postDataJSON());pending=route});await panel.getByRole('button',{name:'تسجيل التحصيل',exact:true}).click();await expect.poll(()=>Boolean(pending)).toBe(true);await expect(panel.getByRole('button',{name:'تسجيل التحصيل',exact:true})).toBeDisabled();expect(state.writes).toHaveLength(1);await page.evaluate(()=>window.HydrolandAuth.terminateSession());await json(pending,{outstandingMinor:6000},201);await expect(panel).toHaveCount(0);
});

test('collection stays unavailable until the accountant opens an active shift',async({page})=>{
 const state=await setup(page);state.detail={...detail(),collectable:false,collectionShiftId:null,payments:{page:1,pageSize:25,total:0,items:[]}};const panel=await open(page);await openDetail(panel);await expect(panel).toContainText('افتح وردية محاسب نشطة');await expect(panel.locator('form[data-ar-operation=collect]')).toHaveCount(0);expect(state.writes).toHaveLength(0);
});
