import {test,expect} from '@playwright/test';
import {openWorkspaceSwitcher} from './portal-test-helpers.js';
const json=(route,body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
async function fixture(page,kind){
 const state={active:true,refreshes:0,reads:0};
 const profile={id:'focused-center',email:'focused@example.invalid',status:'ACTIVE',person:{firstName:'مدير',lastName:'مركز'},roleAssignments:[{role:'DIVE_CENTER',status:'ACTIVE'}]};
 await page.route('**/api/v1/**',route=>{const path=new URL(route.request().url()).pathname;if(path==='/api/v1/me'){state.refreshes++;return json(route,{...profile,roleAssignments:state.active?profile.roleAssignments:[]})}if(path==='/api/v1/me/diver-profile')return json(route,{profile:null,equipment:[]});if(path==='/api/v1/center/me/overview')return json(route,{center:{displayName:'مركز'},metrics:{}});if(path==='/api/v1/center/me/equipment')return json(route,[{resourceId:'eq',resourceName:'معدة',stockStatus:'AVAILABLE'}]);if(path==='/api/v1/center/me/equipment/eq/history'){state.reads++;return json(route,[{movementType:'CHECK_IN'}])}if(path==='/api/v1/center/me/trips')return json(route,[{id:'trip',title:'رحلة',status:'OPEN',_count:{bookings:1}}]);if(path==='/api/v1/center/me/trips/trip/bookings'){state.reads++;return json(route,[{id:'book',status:'CONFIRMED',seats:1,account:{person:{firstName:'عميل'}},participants:[]}])}return json(route,[])});
 await page.goto('/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>Boolean(window.HydrolandAuth&&window.HydrolandProfile&&window.HydrolandCenterEquipment&&window.HydrolandCenterOperations));
 await page.evaluate(async()=>{window.HydrolandAuth.acceptSession({accessToken:'focused-access',refreshToken:'focused-refresh'},window.HydrolandAuth.beginAuthAttempt());await window.HydrolandProfile.load()});await openWorkspaceSwitcher(page);await page.locator('#role-dialog [data-role="center"]').click();
 await page.locator(kind==='equipment'?'[data-portal-label="المعدات والمخزون"]':'[data-portal-label="الرحلات"]').click();return state;
}
test('center equipment sensitive read refreshes role and fails closed after revocation',async({page})=>{const state=await fixture(page,'equipment');const panel=page.locator('#hl-center-equipment');const before=state.refreshes;await panel.locator('[data-equipment-history-button]').click();await expect(panel.locator('[data-equipment-history]')).toContainText('CHECK_IN');expect(state.refreshes).toBeGreaterThan(before);state.active=false;await panel.locator('[data-equipment-history-button]').click();await expect(panel).toHaveCount(0)});
test('center booking identities refresh role and fail closed after revocation',async({page})=>{const state=await fixture(page,'operations');const panel=page.locator('#hl-center-operations');const before=state.refreshes;await panel.locator('[data-center-bookings]').click();await expect(panel.locator('[data-center-booking="book"]')).toContainText('عميل');expect(state.refreshes).toBeGreaterThan(before);state.active=false;await panel.locator('[data-center-bookings]').click();await expect(panel).toHaveCount(0)});