import {test,expect} from '@playwright/test';
import {openWorkspaceSwitcher} from './portal-test-helpers.js';
const json=(route,body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
const trip={id:'trip-edit',title:'رحلة محفوظة',type:'BOAT',startsAt:'2031-02-03T06:00:00.000Z',endsAt:'2031-02-03T10:00:00.000Z',capacity:6,status:'DRAFT',updatedAt:'2026-10-04T01:00:00.000Z',price:{pricePerSeatMinor:12550,currency:'SAR'},location:{locationName:'موقع المركز',latitude:18.2,longitude:41.5},_count:{bookings:0}};
async function setup(page,rows=[{...trip,status:"OPEN"}]){
 const state={active:true,rows,writes:[]};const profile={id:'center-manager',email:'manager@example.invalid',status:'ACTIVE',person:{firstName:'مدير',lastName:'المركز'},roleAssignments:[{role:'DIVE_CENTER',status:'ACTIVE'}]};
 await page.route('**/api/v1/**',route=>json(route,[]));await page.route('**/api/v1/auth/google/config',route=>json(route,{enabled:false}));
 await page.route(/\/api\/v1\/me$/,route=>json(route,{...profile,roleAssignments:state.active?profile.roleAssignments:[]}));await page.route(/\/api\/v1\/me\/diver-profile$/,route=>json(route,{profile:null,equipment:[]}));
 await page.route('**/api/v1/center/me/overview',route=>json(route,{center:{displayName:'عالم الغوص'},metrics:{totalTrips:state.rows.length}}));
 await page.route(/\/api\/v1\/center\/me\/trips$/,route=>{if(route.request().method()==='GET')return json(route,state.rows);const body=route.request().postDataJSON();state.writes.push(body);state.rows=[{...trip,...body,id:body.requestId}];return json(route,state.rows[0],201)});
 await page.goto('/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>Boolean(window.HydrolandCenterOperations&&window.HydrolandAuth&&window.HydrolandProfile));
 await page.evaluate(async()=>{window.HydrolandAuth.acceptSession({accessToken:'trip-access',refreshToken:'trip-refresh'},window.HydrolandAuth.beginAuthAttempt());await window.HydrolandProfile.load()});
 await openWorkspaceSwitcher(page);await page.locator('#role-dialog [data-role="center"]').click();await page.locator('[data-portal-label="الرحلات"]').click();await expect(page.locator('#hl-center-operations')).toBeVisible();await expect(page.locator('#hl-center-operations').getByText('إضافة رحلة',{exact:true})).toBeVisible();return state;
}

const preview={trip:{...trip,status:'OPEN',endsAt:'2026-01-01T10:00:00.000Z'},stateToken:'a'.repeat(64),actions:['CANCEL','CLOSE','COMPLETE'],bookings:{pending:1,confirmed:1,confirmedSeats:2,cancelled:0},participants:[{id:'p-1',fullName:'حاضر <script>',eligibilityStatus:'ELIGIBLE'},{id:'p-2',fullName:'غائب',eligibilityStatus:'ELIGIBLE'}],financial:[{status:'CAPTURED',count:1,amountMinor:12500,currency:'SAR'}],clearance:{status:'ACTIVE'}};
async function lifecycle(page){const state=await setup(page);let value=structuredClone(preview);await page.route('**/api/v1/center/me/trips/trip-edit/lifecycle',route=>json(route,value));await page.locator('[data-center-trip-lifecycle]').click();const box=page.locator('[data-trip-lifecycle]');await expect(box.getByRole('heading',{name:'إجراءات الرحلة'})).toBeVisible();return{state,box,setPreview:next=>{value=next}};}
async function actionForm(box,action){const form=box.locator(`[data-trip-lifecycle-form][data-action=${action}]`);await form.locator('..').locator('summary').click();await form.locator('[name=reason]').fill('سبب الإجراء موثق للاختبار');if(['CANCEL','COMPLETE'].includes(action))await form.locator('[name=financialAcknowledged]').check();return form;}
test('lifecycle shows financial impact and never assumes attendance',async({page})=>{const{box}=await lifecycle(page);await expect(box).toContainText('125.00 SAR');await expect(box).toContainText('لا يعني استرداد المبلغ');const form=await actionForm(box,'COMPLETE');await expect(form.locator('[name=attendedParticipantIds]:checked')).toHaveCount(0);await expect(form).toContainText('حاضر <script>');expect(await form.locator('script').count()).toBe(0);});
test('cancel sends reviewed state and acknowledgement then refreshes trip',async({page})=>{const{box,state}=await lifecycle(page);let body;await page.route('**/api/v1/center/me/trips/trip-edit/actions',route=>{body=route.request().postDataJSON();state.rows=[{...trip,status:'CANCELLED'}];return json(route,{trip:{id:trip.id,status:'CANCELLED'}},201)});const form=await actionForm(box,'CANCEL');await form.locator('[type=submit]').click();await expect(page.locator('#hl-center-operations')).toContainText('تم حفظ إجراء الرحلة');expect(body).toMatchObject({action:'CANCEL',expectedUpdatedAt:trip.updatedAt,expectedState:preview.stateToken,financialAcknowledged:true});expect(body.requestId).toMatch(/^[0-9a-f-]{36}$/);expect(body).not.toHaveProperty('organizationId');await expect(page.locator('[data-center-trip]')).toContainText('ملغاة');});
test('completion submits only explicit attendee with measured dive data',async({page})=>{const{box,state}=await lifecycle(page);let body;await page.route('**/api/v1/center/me/trips/trip-edit/actions',route=>{body=route.request().postDataJSON();state.rows=[{...trip,status:'COMPLETED'}];return json(route,{createdDiveLogs:1},201)});const form=await actionForm(box,'COMPLETE');for(const[name,value]of Object.entries({siteName:'موقع عالم الغوص',maxDepthM:'12',durationMin:'35'}))await form.locator(`[name=${name}]`).fill(value);await form.locator('[type=submit]').click();await expect(form.locator('[data-trip-action-feedback]')).toContainText('حدد مشاركًا');expect(body).toBeUndefined();await form.locator('[name=attendedParticipantIds]').first().check();await form.locator('[type=submit]').click();await expect(page.locator('#hl-center-operations')).toContainText('تم حفظ إجراء الرحلة');expect(body).toMatchObject({action:'COMPLETE',attendedParticipantIds:['p-1'],maxDepthM:12,durationMin:35,siteName:'موقع عالم الغوص'});});
test('stale financial preview preserves inputs and requires explicit refresh',async({page})=>{const{box,setPreview}=await lifecycle(page);await page.route('**/api/v1/center/me/trips/trip-edit/actions',route=>json(route,{message:'تغيرت الرحلة أو مدفوعاتها'},409));const form=await actionForm(box,'CANCEL');await form.locator('[type=submit]').click();await expect(form.locator('[data-trip-action-feedback]')).toContainText('تحديث التفاصيل');await expect(form.locator('[name=reason]')).toHaveValue('سبب الإجراء موثق للاختبار');setPreview({...preview,stateToken:'b'.repeat(64),financial:[{status:'CAPTURED',count:2,amountMinor:25000,currency:'SAR'}]});await box.getByRole('button',{name:'تحديث التفاصيل',exact:true}).click();await expect(box).toContainText('250.00 SAR');await expect(box.locator('[data-action=CANCEL] [name=reason]')).toHaveValue('');});
test('failed lifecycle write retries with the same request identity',async({page})=>{const{box}=await lifecycle(page),writes=[];await page.route('**/api/v1/center/me/trips/trip-edit/actions',route=>{writes.push(route.request().postDataJSON());return json(route,{message:'تعذر الحفظ مؤقتًا'},503)});const form=await actionForm(box,'CANCEL');for(let i=0;i<2;i++){await form.locator('[type=submit]').click();await expect(form.locator('[data-trip-action-feedback]')).toContainText('تعذر الحفظ');await expect(form.locator('[type=submit]')).toBeEnabled()}expect(writes).toHaveLength(2);expect(writes[0]).toEqual(writes[1]);});
test('revoked center role cannot submit lifecycle action',async({page})=>{const{box,state}=await lifecycle(page);let writes=0;await page.route('**/api/v1/center/me/trips/trip-edit/actions',route=>{writes++;return json(route,{},201)});const form=await actionForm(box,'CANCEL');state.active=false;await form.evaluate(node=>node.requestSubmit());await expect(page.locator('#hl-center-operations')).toHaveCount(0);expect(writes).toBe(0);});
