INSERT INTO "PolicyControl" ("id","category","ruleKey","labelAr","labelEn","state","description") VALUES
(gen_random_uuid()::text,'INSTRUCTOR','ACTIVE_ROLE','الدور النشط للمدرب','Active instructor role','ENABLED','التحقق من أن دور المدرب نشط قبل إسناد التدريب أو الرحلات.'),
(gen_random_uuid()::text,'INSTRUCTOR','VERIFIED_CREDENTIAL','اعتماد المدرب الموثق','Verified instructor credential','ENABLED','التحقق من وجود اعتماد مدرب موثق وساري.'),
(gen_random_uuid()::text,'CAPTAIN','ACTIVE_ROLE','الدور التشغيلي للكابتن','Active captain role','ENABLED','التحقق من وجود دور تشغيلي نشط للكابتن.'),
(gen_random_uuid()::text,'CAPTAIN','VERIFIED_LICENSE','رخصة الكابتن الموثقة','Verified captain license','REVIEW','التحقق من الرخصة البحرية المناسبة وصلاحيتها؛ يبقى تحت المراجعة حتى اكتمال تصنيف أنواع الرخص.'),
(gen_random_uuid()::text,'CREW','ACTIVE_ROLE','الدور النشط للطاقم','Active crew role','ENABLED','التحقق من أن عضو الطاقم مرتبط بدور تشغيلي نشط.'),
(gen_random_uuid()::text,'BOAT','REGISTRATION','تسجيل الوسيلة البحرية','Boat registration','REVIEW','التحقق من تسجيل وقيد الوسيلة البحرية وفق التصنيف التشغيلي.'),
(gen_random_uuid()::text,'BOAT','NAVIGATION_LICENSE','الترخيص الملاحي','Navigation license','REVIEW','التحقق من سريان الترخيص الملاحي أو رخصة العمل بحسب الاستخدام.'),
(gen_random_uuid()::text,'BOAT','SAFETY_CERTIFICATES','شهادات سلامة القارب','Boat safety certificates','REVIEW','التحقق من المعاينات وشهادات السلامة السارية.'),
(gen_random_uuid()::text,'BOAT','PASSENGER_LIMIT','الحد المصرح للأشخاص','Authorized passenger limit','ENABLED','منع تجاوز الحد التشغيلي المصرح للأشخاص أو الركاب.'),
(gen_random_uuid()::text,'EQUIPMENT','INSPECTION_STATUS','حالة فحص المعدات','Equipment inspection status','REVIEW','التحقق من فحص المعدات الحرجة قبل تخصيصها للرحلة.'),
(gen_random_uuid()::text,'EQUIPMENT','SERVICE_EXPIRY','صلاحية صيانة المعدات','Equipment service validity','REVIEW','التحقق من عدم انتهاء دورة الصيانة أو الخدمة للمعدات.'),
(gen_random_uuid()::text,'DOCUMENT','VERIFICATION','توثيق المستندات','Document verification','ENABLED','التحقق من حالة توثيق المستندات المطلوبة قبل الاعتماد.'),
(gen_random_uuid()::text,'DOCUMENT','EXPIRY','صلاحية المستندات','Document expiry','ENABLED','التحقق من أن المستندات والتراخيص المطلوبة غير منتهية.'),
(gen_random_uuid()::text,'CENTER','ACTIVATION_APPROVAL','اعتماد تفعيل مركز الغوص','Dive center activation approval','ENABLED','يتحكم في اعتماد المركز قبل تفعيل خدماته.'),
(gen_random_uuid()::text,'CENTER','LICENSES','تراخيص مركز الغوص','Dive center licenses','REVIEW','التحقق من التراخيص النظامية المطلوبة حسب الخدمة والمنطقة.'),
(gen_random_uuid()::text,'ORGANIZATION','ACTIVATION_APPROVAL','اعتماد تفعيل الجهات','Organization activation approval','ENABLED','يتحكم في اعتماد الجهات والشركات قبل تفعيل الحساب المؤسسي.'),
(gen_random_uuid()::text,'ORGANIZATION','REGISTRATION_DOCUMENTS','وثائق تسجيل الجهة','Organization registration documents','REVIEW','التحقق من وثائق التسجيل والتمثيل النظامي للجهة.'),
(gen_random_uuid()::text,'TRAINING','INSTRUCTOR_ELIGIBILITY','أهلية المدرب للدورة','Instructor eligibility for course','ENABLED','التحقق من أهلية المدرب قبل إسناد دورة أو طالب.'),
(gen_random_uuid()::text,'TRAINING','STUDENT_PREREQUISITES','متطلبات الطالب السابقة','Student prerequisites','REVIEW','التحقق من المتطلبات السابقة للدورة قبل التسجيل النهائي.'),
(gen_random_uuid()::text,'PAYMENT','PAYMENT_REQUIRED','اشتراط الدفع','Payment required','REVIEW','يتحكم في اشتراط حالة دفع صالحة قبل تأكيد الخدمات المدفوعة؛ يبقى تحت المراجعة حتى اختيار مزود الدفع.'),
(gen_random_uuid()::text,'PAYMENT','REFUND_REVIEW','مراجعة الاسترداد','Refund review','REVIEW','إحالة طلبات الاسترداد للمراجعة حسب سياسة الخدمة.'),
(gen_random_uuid()::text,'COMPLIANCE','REGULATORY_REVIEW','المراجعة النظامية','Regulatory review','REVIEW','يتحكم في إحالة المتطلبات النظامية غير المحسومة للمراجعة الإدارية.'),
(gen_random_uuid()::text,'COMPLIANCE','PERMIT_REQUIRED','اشتراط التصريح','Permit required','REVIEW','التحقق من التصريح المطلوب للرحلة أو النشاط عندما ينطبق.'),
(gen_random_uuid()::text,'SECURITY','ACCOUNT_STATUS','حالة الحساب','Account status','ENABLED','منع الحسابات الموقوفة أو المؤرشفة من العمليات المحمية.'),
(gen_random_uuid()::text,'MEDICAL','FIT_TO_DIVE','اللياقة الطبية للغوص','Fit-to-dive clearance','ENABLED','التحقق من حالة اللياقة للغوص دون تخزين أو كشف تشخيصات طبية.'),
(gen_random_uuid()::text,'IDENTITY','IDENTITY_VERIFICATION','توثيق الهوية','Identity verification','REVIEW','التحقق من حالة توثيق الهوية عند العمليات التي تتطلب ذلك.')
ON CONFLICT ("category","ruleKey") DO NOTHING;