ALTER TYPE "WorkforceHiringRequestStatus" ADD VALUE 'PENDING_HR_REVIEW' BEFORE 'PENDING_EXECUTIVE_APPROVAL';
ALTER TYPE "WorkforceHiringRequestStatus" ADD VALUE 'HR_CHANGES_REQUIRED' BEFORE 'PENDING_EXECUTIVE_APPROVAL';
CREATE TYPE "WorkforceHiringRequestSource" AS ENUM ('CANDIDATE', 'CENTER_MANAGER', 'HUMAN_RESOURCES');
