-- HYDROLAND canonical HR lifecycle migration.
-- Existing Prisma String @default(uuid()) identifiers are PostgreSQL TEXT; keep all HR PK/FK identifiers TEXT.
CREATE TYPE "OrgUnitType" AS ENUM ('HQ','REGION','CENTER','DEPARTMENT','UNIT','TEAM');
CREATE TYPE "EmploymentStatus" AS ENUM ('DRAFT','PENDING_APPROVAL','ACTIVE','ON_LEAVE','SUSPENDED','TERMINATED','OFFBOARDED');
CREATE TYPE "WorkerClass" AS ENUM ('EMPLOYEE','TEMPORARY_WORKER','INDEPENDENT_PROFESSIONAL','CONTRACTOR','CENTER_AFFILIATED','TRIP_ONLY');
CREATE TYPE "EmploymentMovementType" AS ENUM ('APPOINTMENT','TRANSFER','TEMPORARY_ASSIGNMENT','PROMOTION','DEMOTION','SUSPENSION','RETURN_TO_ROLE','TERMINATION');
CREATE TYPE "HrRequestStatus" AS ENUM ('DRAFT','SUBMITTED','HR_REVIEW','APPROVAL_REQUIRED','APPROVED','REJECTED','CANCELLED','EFFECTIVE','CLOSED');

CREATE TABLE "OrgUnit" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"parentId" TEXT,"type" "OrgUnitType" NOT NULL,"code" TEXT NOT NULL,"nameAr" TEXT NOT NULL,"nameEn" TEXT,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "OrgUnit_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "OrgUnit_organizationId_code_key" ON "OrgUnit"("organizationId","code");
CREATE INDEX "OrgUnit_organizationId_parentId_type_idx" ON "OrgUnit"("organizationId","parentId","type");
CREATE TABLE "Position" ("id" TEXT NOT NULL,"orgUnitId" TEXT NOT NULL,"code" TEXT NOT NULL,"titleAr" TEXT NOT NULL,"titleEn" TEXT,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Position_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Position_orgUnitId_code_key" ON "Position"("orgUnitId","code");
CREATE TABLE "Employment" ("id" TEXT NOT NULL,"accountId" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"orgUnitId" TEXT NOT NULL,"positionId" TEXT,"managerEmploymentId" TEXT,"workerClass" "WorkerClass" NOT NULL,"status" "EmploymentStatus" NOT NULL DEFAULT 'DRAFT',"startsAt" TIMESTAMP(3),"endsAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Employment_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Employment_accountId_status_idx" ON "Employment"("accountId","status");
CREATE INDEX "Employment_organizationId_orgUnitId_status_idx" ON "Employment"("organizationId","orgUnitId","status");
CREATE TABLE "EmploymentContract" ("id" TEXT NOT NULL,"employmentId" TEXT NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"contractType" TEXT NOT NULL,"effectiveFrom" TIMESTAMP(3) NOT NULL,"effectiveTo" TIMESTAMP(3),"documentId" TEXT,"status" TEXT NOT NULL DEFAULT 'DRAFT',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "EmploymentContract_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "EmploymentContract_employmentId_version_key" ON "EmploymentContract"("employmentId","version");
CREATE TABLE "EmploymentMovement" ("id" TEXT NOT NULL,"employmentId" TEXT NOT NULL,"type" "EmploymentMovementType" NOT NULL,"status" "HrRequestStatus" NOT NULL DEFAULT 'DRAFT',"fromOrgUnitId" TEXT,"toOrgUnitId" TEXT,"fromPositionId" TEXT,"toPositionId" TEXT,"requestedByAccountId" TEXT NOT NULL,"reviewedByAccountId" TEXT,"approvedByAccountId" TEXT,"effectiveAt" TIMESTAMP(3),"reason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "EmploymentMovement_pkey" PRIMARY KEY ("id"));
CREATE INDEX "EmploymentMovement_employmentId_status_idx" ON "EmploymentMovement"("employmentId","status");
CREATE TABLE "LeaveRequest" ("id" TEXT NOT NULL,"employmentId" TEXT NOT NULL,"type" TEXT NOT NULL,"status" "HrRequestStatus" NOT NULL DEFAULT 'DRAFT',"startsAt" TIMESTAMP(3) NOT NULL,"endsAt" TIMESTAMP(3) NOT NULL,"requestedByAccountId" TEXT NOT NULL,"approvedByAccountId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "LeaveRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AttendanceEntry" ("id" TEXT NOT NULL,"employmentId" TEXT NOT NULL,"workDate" DATE NOT NULL,"clockInAt" TIMESTAMP(3),"clockOutAt" TIMESTAMP(3),"status" TEXT NOT NULL DEFAULT 'PENDING',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "AttendanceEntry_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "AttendanceEntry_employmentId_workDate_key" ON "AttendanceEntry"("employmentId","workDate");
CREATE TABLE "ShiftAssignment" ("id" TEXT NOT NULL,"employmentId" TEXT NOT NULL,"startsAt" TIMESTAMP(3) NOT NULL,"endsAt" TIMESTAMP(3) NOT NULL,"shiftCode" TEXT,"status" TEXT NOT NULL DEFAULT 'SCHEDULED',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ShiftAssignment_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ShiftAssignment_employmentId_startsAt_idx" ON "ShiftAssignment"("employmentId","startsAt");
CREATE INDEX "ShiftAssignment_status_idx" ON "ShiftAssignment"("status");
CREATE TABLE "CompensationTerm" ("id" TEXT NOT NULL,"employmentId" TEXT NOT NULL,"effectiveFrom" TIMESTAMP(3) NOT NULL,"effectiveTo" TIMESTAMP(3),"baseAmountMinor" INTEGER,"currency" TEXT NOT NULL DEFAULT 'SAR',"allowances" JSONB,"benefits" JSONB,"status" "HrRequestStatus" NOT NULL DEFAULT 'DRAFT',"approvedByAccountId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "CompensationTerm_pkey" PRIMARY KEY ("id"));
CREATE INDEX "CompensationTerm_employmentId_effectiveFrom_idx" ON "CompensationTerm"("employmentId","effectiveFrom");
CREATE INDEX "CompensationTerm_status_idx" ON "CompensationTerm"("status");
CREATE TABLE "PerformanceCycle" ("id" TEXT NOT NULL,"employmentId" TEXT NOT NULL,"periodStart" DATE NOT NULL,"periodEnd" DATE NOT NULL,"status" TEXT NOT NULL DEFAULT 'DRAFT',"goals" JSONB,"managerAssessment" JSONB,"hrReview" JSONB,"developmentPlan" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "PerformanceCycle_pkey" PRIMARY KEY ("id"));
CREATE TABLE "EmployeeRelationsCase" ("id" TEXT NOT NULL,"employmentId" TEXT NOT NULL,"caseType" TEXT NOT NULL,"status" "HrRequestStatus" NOT NULL DEFAULT 'DRAFT',"openedByAccountId" TEXT NOT NULL,"reviewedByAccountId" TEXT,"approvedByAccountId" TEXT,"summary" TEXT,"decision" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "EmployeeRelationsCase_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OffboardingCase" ("id" TEXT NOT NULL,"employmentId" TEXT NOT NULL,"status" "HrRequestStatus" NOT NULL DEFAULT 'DRAFT',"reason" TEXT,"lastWorkingAt" TIMESTAMP(3),"clearance" JSONB,"iamRevokedAt" TIMESTAMP(3),"closedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "OffboardingCase_pkey" PRIMARY KEY ("id"));

ALTER TABLE "OrgUnit" ADD CONSTRAINT "OrgUnit_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OrgUnit" ADD CONSTRAINT "OrgUnit_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "OrgUnit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Position" ADD CONSTRAINT "Position_orgUnitId_fkey" FOREIGN KEY ("orgUnitId") REFERENCES "OrgUnit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Employment" ADD CONSTRAINT "Employment_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Employment" ADD CONSTRAINT "Employment_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Employment" ADD CONSTRAINT "Employment_orgUnitId_fkey" FOREIGN KEY ("orgUnitId") REFERENCES "OrgUnit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Employment" ADD CONSTRAINT "Employment_positionId_fkey" FOREIGN KEY ("positionId") REFERENCES "Position"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Employment" ADD CONSTRAINT "Employment_managerEmploymentId_fkey" FOREIGN KEY ("managerEmploymentId") REFERENCES "Employment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmploymentContract" ADD CONSTRAINT "EmploymentContract_employmentId_fkey" FOREIGN KEY ("employmentId") REFERENCES "Employment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmploymentContract" ADD CONSTRAINT "EmploymentContract_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmploymentMovement" ADD CONSTRAINT "EmploymentMovement_employmentId_fkey" FOREIGN KEY ("employmentId") REFERENCES "Employment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmploymentMovement" ADD CONSTRAINT "EmploymentMovement_fromOrgUnitId_fkey" FOREIGN KEY ("fromOrgUnitId") REFERENCES "OrgUnit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmploymentMovement" ADD CONSTRAINT "EmploymentMovement_toOrgUnitId_fkey" FOREIGN KEY ("toOrgUnitId") REFERENCES "OrgUnit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmploymentMovement" ADD CONSTRAINT "EmploymentMovement_fromPositionId_fkey" FOREIGN KEY ("fromPositionId") REFERENCES "Position"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmploymentMovement" ADD CONSTRAINT "EmploymentMovement_toPositionId_fkey" FOREIGN KEY ("toPositionId") REFERENCES "Position"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmploymentMovement" ADD CONSTRAINT "EmploymentMovement_requestedByAccountId_fkey" FOREIGN KEY ("requestedByAccountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmploymentMovement" ADD CONSTRAINT "EmploymentMovement_reviewedByAccountId_fkey" FOREIGN KEY ("reviewedByAccountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmploymentMovement" ADD CONSTRAINT "EmploymentMovement_approvedByAccountId_fkey" FOREIGN KEY ("approvedByAccountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LeaveRequest" ADD CONSTRAINT "LeaveRequest_employmentId_fkey" FOREIGN KEY ("employmentId") REFERENCES "Employment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LeaveRequest" ADD CONSTRAINT "LeaveRequest_requestedByAccountId_fkey" FOREIGN KEY ("requestedByAccountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LeaveRequest" ADD CONSTRAINT "LeaveRequest_approvedByAccountId_fkey" FOREIGN KEY ("approvedByAccountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AttendanceEntry" ADD CONSTRAINT "AttendanceEntry_employmentId_fkey" FOREIGN KEY ("employmentId") REFERENCES "Employment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ShiftAssignment" ADD CONSTRAINT "ShiftAssignment_employmentId_fkey" FOREIGN KEY ("employmentId") REFERENCES "Employment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CompensationTerm" ADD CONSTRAINT "CompensationTerm_employmentId_fkey" FOREIGN KEY ("employmentId") REFERENCES "Employment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CompensationTerm" ADD CONSTRAINT "CompensationTerm_approvedByAccountId_fkey" FOREIGN KEY ("approvedByAccountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PerformanceCycle" ADD CONSTRAINT "PerformanceCycle_employmentId_fkey" FOREIGN KEY ("employmentId") REFERENCES "Employment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmployeeRelationsCase" ADD CONSTRAINT "EmployeeRelationsCase_employmentId_fkey" FOREIGN KEY ("employmentId") REFERENCES "Employment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmployeeRelationsCase" ADD CONSTRAINT "EmployeeRelationsCase_openedByAccountId_fkey" FOREIGN KEY ("openedByAccountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmployeeRelationsCase" ADD CONSTRAINT "EmployeeRelationsCase_reviewedByAccountId_fkey" FOREIGN KEY ("reviewedByAccountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmployeeRelationsCase" ADD CONSTRAINT "EmployeeRelationsCase_approvedByAccountId_fkey" FOREIGN KEY ("approvedByAccountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OffboardingCase" ADD CONSTRAINT "OffboardingCase_employmentId_fkey" FOREIGN KEY ("employmentId") REFERENCES "Employment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
