import { BadRequestException, Injectable } from '@nestjs/common';
import { DOCUMENT_DEPARTMENTS, DocumentRecord, DocumentTemplate } from './document-form.domain';
@Injectable()
export class DocumentFormService {
 validateTemplate(t:DocumentTemplate){ if(!t.id||!t.organizationId||!t.code?.trim()||!t.titleAr?.trim()||!t.titleEn?.trim()) throw new BadRequestException('Document template identity, scope, code and bilingual titles are required.'); if(!DOCUMENT_DEPARTMENTS.includes(t.department)) throw new BadRequestException('Unsupported document department.'); if(!Number.isInteger(t.version)||t.version<1) throw new BadRequestException('Document template version must be positive.'); if(!t.fields.length) throw new BadRequestException('Document template requires fields.'); const keys=t.fields.map(f=>f.key); if(new Set(keys).size!==keys.length) throw new BadRequestException('Document field keys must be unique.'); for(const f of t.fields){ if(!f.key?.trim()||!f.labelAr?.trim()||!f.labelEn?.trim()) throw new BadRequestException('Document fields require key and bilingual labels.'); if(f.type==='SELECT'&&!f.options?.length) throw new BadRequestException('Select fields require options.'); } return t; }
 createRecord(t:DocumentTemplate,input:Omit<DocumentRecord,'templateId'|'templateVersion'|'department'|'status'>):DocumentRecord { this.validateTemplate(t); if(!t.active) throw new BadRequestException('Inactive document template cannot create records.'); if(input.organizationId!==t.organizationId) throw new BadRequestException('Document organization scope mismatch.'); if(!input.referenceType||!input.referenceId||!input.createdByAccountId) throw new BadRequestException('Document reference and creator are required.'); this.validateValues(t,input.values); return {...input,templateId:t.id,templateVersion:t.version,department:t.department,status:'DRAFT'}; }
 finalize(t:DocumentTemplate,r:DocumentRecord,actorId:string):DocumentRecord { if(r.status!=='DRAFT'||!actorId) throw new BadRequestException('Draft document and finalizer are required.'); if(r.organizationId!==t.organizationId||r.templateId!==t.id||r.templateVersion!==t.version||r.department!==t.department) throw new BadRequestException('Document template scope mismatch.'); this.validateValues(t,r.values); return {...r,status:'FINAL',finalizedByAccountId:actorId,finalizedAt:new Date()}; }
 assertPrintable(t:DocumentTemplate,r:DocumentRecord){ if(!t.printable||r.status!=='FINAL') throw new BadRequestException('Only final records from printable templates can be printed.'); if(r.organizationId!==t.organizationId||r.templateId!==t.id) throw new BadRequestException('Printable document scope mismatch.'); return true; }
 private validateValues(t:DocumentTemplate,v:Record<string,unknown>){ for(const f of t.fields) if(f.required&&(v[f.key]===undefined||v[f.key]===null||v[f.key]==='')) throw new BadRequestException(`Required document field missing: ${f.key}`); const allowed=new Set(t.fields.map(f=>f.key)); for(const k of Object.keys(v)) if(!allowed.has(k)) throw new BadRequestException(`Unknown document field: ${k}`); }
}
